### ISSUE TITLE
Why does `run_for_cloud_option.sh` need FastChat?

### ISSUE THREAD

**Issue by thiner** [netease-youdao/QAnything#101]
Why does `run_for_cloud_option.sh` need check checksum of FastChat? 
```
# 获取默认的 MD5 校验和
default_checksum=$(cat /workspace/qanything_local/third_party/checksum.config)

# 计算FastChat文件夹下所有文件的 MD5 校验和
checksum=$(find /workspace/qanything_local/third_party/FastChat -type f -exec md5sum {} + | awk '{print $1}' | sort | md5sum | awk '{print $1}')

```
I was trying to test QAnything with my existing OpenAI compatible LLM service, it should depend on any other LLM modules in my opinion.

**Comment by songkq** [comment]
@thiner Not necessary, just to align with the deployment environment of `run_for_local_option.sh`.

**Comment by thiner** [comment]
but it's causing error while starting up the docker image. The error message says it can't find this fastchat dependency, thus failed to start.

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by songkq** [comment]
@thiner  Please give the startup command and the complete log for debugging.  By the way, which version of docker image do you use?

**Comment by zhangwenhao666** [comment]
I also encountered the same problem. It timed out when loading LLM. The error reported in fachat_model_worker_7801.log is as follows:2024-02-05 09:47:17 | INFO | model_worker | Loading the model ['Qwen-7B-QAnything'] on worker e2bf5ea2 ...
2024-02-05 09:47:17 | INFO | stdout | Warning: import flash_attn rotary fail, please install FlashAttention rotary to get better performance https://github.com/Dao-AILab/flash-attention/tree/main/csrc/rotary
2024-02-05 09:47:17 | INFO | stdout | Warning: import flash_attn rms_norm fail, please install FlashAttention layer_norm to get better performance https://github.com/Dao-AILab/flash-attention/tree/main/csrc/layer_norm
2024-02-05 09:47:17 | INFO | stdout | Warning: import flash_attn fail, please install FlashAttention https://github.com/Dao-AILab/flash-attention
2024-02-05 09:47:19 | ERROR | stderr | 
  0%|          | 0/2 [00:00<?, ?it/s]
2024-02-05 09:47:19 | ERROR | stderr | 
  0%|          | 0/2 [00:00<?, ?it/s]
2024-02-05 09:47:19 | ERROR | stderr | 
2024-02-05 09:47:19 | ERROR | stderr | Traceback (most recent call last):
2024-02-05 09:47:19 | ERROR | stderr |   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
2024-02-05 09:47:19 | ERROR | stderr |     return _run_code(code, main_globals, None,
2024-02-05 09:47:19 | ERROR | stderr |   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
2024-02-05 09:47:19 | ERROR | stderr |     exec(code, run_globals)
2024-02-05 09:47:19 | ERROR | stderr |   File "/workspace/qanything_local/third_party/FastChat/fastchat/serve/model_worker.py", line 375, in <module>
2024-02-05 09:47:19 | ERROR | stderr |     args, worker = create_model_worker()
2024-02-05 09:47:19 | ERROR | stderr |   File "/workspace/qanything_local/third_party/FastChat/fastchat/serve/model_worker.py", line 346, in create_model_worker
2024-02-05 09:47:19 | ERROR | stderr |     worker = ModelWorker(
2024-02-05 09:47:19 | ERROR | stderr |   File "/workspace/qanything_local/third_party/FastChat/fastchat/serve/model_worker.py", line 77, in __init__
2024-02-05 09:47:19 | ERROR | stderr |     self.model, self.tokenizer = load_model(
2024-02-05 09:47:19 | ERROR | stderr |   File "/workspace/qanything_local/third_party/FastChat/fastchat/model/model_adapter.py", line 277, in load_model
2024-02-05 09:47:19 | ERROR | stderr |     model, tokenizer = adapter.load_compress_model(
2024-02-05 09:47:19 | ERROR | stderr |   File "/workspace/qanything_local/third_party/FastChat/fastchat/model/model_adapter.py", line 111, in load_compress_model
2024-02-05 09:47:19 | ERROR | stderr |     return load_compress_model(
2024-02-05 09:47:19 | ERROR | stderr |   File "/workspace/qanything_local/third_party/FastChat/fastchat/model/compression.py", line 189, in load_compress_model
2024-02-05 09:47:19 | ERROR | stderr |     tmp_state_dict = torch.load(
2024-02-05 09:47:19 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1028, in load
2024-02-05 09:47:19 | ERROR | stderr |     return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
2024-02-05 09:47:19 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1246, in _legacy_load
2024-02-05 09:47:19 | ERROR | stderr |     magic_number = pickle_module.load(f, **pickle_load_args)
2024-02-05 09:47:19 | ERROR | stderr | _pickle.UnpicklingError: invalid load key, 'v'.

**Comment by zhangwenhao666** [comment]
> I also encountered the same problem. It timed out when loading LLM. The error reported in fachat_model_worker_7801.log is as follows:2024-02-05 09:47:17 | INFO | model_worker | Loading the model ['Qwen-7B-QAnything'] on worker e2bf5ea2 ... 2024-02-05 09:47:17 | INFO | stdout | Warning: import flash_attn rotary fail, please install FlashAttention rotary to get better performance https://github.com/Dao-AILab/flash-attention/tree/main/csrc/rotary 2024-02-05 09:47:17 | INFO | stdout | Warning: import flash_attn rms_norm fail, please install FlashAttention layer_norm to get better performance https://github.com/Dao-AILab/flash-attention/tree/main/csrc/layer_norm 2024-02-05 09:47:17 | INFO | stdout | Warning: import flash_attn fail, please install FlashAttention https://github.com/Dao-AILab/flash-attention 2024-02-05 09:47:19 | ERROR | stderr | 0%| | 0/2 [00:00<?, ?it/s] 2024-02-05 09:47:19 | ERROR | stderr | 0%| | 0/2 [00:00<?, ?it/s] 2024-02-05 09:47:19 | ERROR | stderr | 2024-02-05 09:47:19 | ERROR | stderr | Traceback (most recent call last): 2024-02-05 09:47:19 | ERROR | stderr | File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main 2024-02-05 09:47:19 | ERROR | stderr | return _run_code(code, main_globals, None, 2024-02-05 09:47:19 | ERROR | stderr | File "/usr/lib/python3.10/runpy.py", line 86, in _run_code 2024-02-05 09:47:19 | ERROR | stderr | exec(code, run_globals) 2024-02-05 09:47:19 | ERROR | stderr | File "/workspace/qanything_local/third_party/FastChat/fastchat/serve/model_worker.py", line 375, in 2024-02-05 09:47:19 | ERROR | stderr | args, worker = create_model_worker() 2024-02-05 09:47:19 | ERROR | stderr | File "/workspace/qanything_local/third_party/FastChat/fastchat/serve/model_worker.py", line 346, in create_model_worker 2024-02-05 09:47:19 | ERROR | stderr | worker = ModelWorker( 2024-02-05 09:47:19 | ERROR | stderr | File "/workspace/qanything_local/third_party/FastChat/fastchat/serve/model_worker.py", line 77, in **init** 2024-02-05 09:47:19 | ERROR | stderr | self.model, self.tokenizer = load_model( 2024-02-05 09:47:19 | ERROR | stderr | File "/workspace/qanything_local/third_party/FastChat/fastchat/model/model_adapter.py", line 277, in load_model 2024-02-05 09:47:19 | ERROR | stderr | model, tokenizer = adapter.load_compress_model( 2024-02-05 09:47:19 | ERROR | stderr | File "/workspace/qanything_local/third_party/FastChat/fastchat/model/model_adapter.py", line 111, in load_compress_model 2024-02-05 09:47:19 | ERROR | stderr | return load_compress_model( 2024-02-05 09:47:19 | ERROR | stderr | File "/workspace/qanything_local/third_party/FastChat/fastchat/model/compression.py", line 189, in load_compress_model 2024-02-05 09:47:19 | ERROR | stderr | tmp_state_dict = torch.load( 2024-02-05 09:47:19 | ERROR | stderr | File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1028, in load 2024-02-05 09:47:19 | ERROR | stderr | return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args) 2024-02-05 09:47:19 | ERROR | stderr | File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1246, in _legacy_load 2024-02-05 09:47:19 | ERROR | stderr | magic_number = pickle_module.load(f, **pickle_load_args) 2024-02-05 09:47:19 | ERROR | stderr | _pickle.UnpicklingError: invalid load key, 'v'.

my docker version is :
Server: Docker Desktop 4.26.1 (131620)
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:08:02 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.25
  GitCommit:        d8f198a4ed8892c764191ef7b3b06d8a2eeb5c7f
 runc:
  Version:          1.1.10
  GitCommit:        v1.1.10-0-g18a0cb0
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by songkq** [comment]
@thiner ```bash ./run.sh -c cloud -i 0 -b default``` to starup QAnything instead.

**Comment by songkq** [comment]
@zhangwenhao666 Please git pull the newest master and starup following this way.

```
## Step 1. Download the public LLM model (e.g., Qwen-7B-QAnything) and save to "/path/to/QAnything/assets/custom_models"
## (Optional) Download Qwen-7B-QAnything from ModelScope: https://www.modelscope.cn/models/netease-youdao/Qwen-7B-QAnything
## (Optional) Download Qwen-7B-QAnything from Huggingface: https://huggingface.co/netease-youdao/Qwen-7B-QAnything
cd /path/to/QAnything/assets/custom_models
git clone https://huggingface.co/netease-youdao/Qwen-7B-QAnything

## Step 2. Execute the service startup command.  Here we use "-b hf" to specify the Huggingface transformers backend.
## Here we use "-b hf" to specify the transformers backend that will load model in 8 bits but do bf16 inference as default for saving VRAM.
cd /path/to/QAnything
bash ./run.sh -c local -i 0 -b hf -m Qwen-7B-QAnything -t qwen-7b-qanything
```

**Comment by thiner** [comment]
> ./run.sh

I tried, but not working. 
```
 /bin/bash: /workspace/qanything_local/run.sh: No such file or directory
```
Please note, I am running the docker image. I checked the files inside the container, there is not such a `run.sh` in folder `qanything_local`  indeed.

**Comment by songkq** [comment]
@thiner  `bash ./run.sh -c cloud -i 0 -b default` to startup QAnything in the `host environment` instead of the Docker container. 
The startup script `run.sh` will start all dependent containers(`milvus-etcd-local, milvus-minio-local, milvus-standalone-local, mysql-container-local, and qanything-container-local`) automatically by `docker-compose -p user -f docker-compose-linux.yaml up -d`.

**Comment by thiner** [comment]
OK, thanks for telling me how to run on desktop or docker-compose. But I deployed QAnything in k8s cluster. The problem is that it depends on redundant components while connecting to existing cloud API.

**Comment by songkq** [comment]
@thiner Not supported K8s deployment yet,  please look forward to the future.

**Comment by thiner** [comment]
@songkq thanks for the clarification. But I am not asking for support for k8s. I am wondering why the script for running against OpenAI API depends on FastChat? IMHO, `run_for_cloud_option.sh` is designed for non-local integration, it should skip those checksum steps for FastChat. Thus, the problem should be fixed.

**Comment by songkq** [comment]
@thiner Yeah. FastChat dependencies have been removed in the newest version, coming soon.

**Comment by granthe2761** [comment]
@songkq I would like to know if the `run_for_cloud_option.sh` script can be configured to remotely call the QWEN14B and QWEN72B models already deployed on our intranet? I understand that it seems to be possible to call Qwen as OpenAI API via one-api. If this is possible, do I need to change the model configuration file?
