### ISSUE TITLE
[BUG] < mysql-container-local>  mysql-container-loca容器闪退，

### ISSUE THREAD

**Issue by bestlee666** [netease-youdao/QAnything#148]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### mysql-container-local

(base) lihuan@Leon:/media/462EF2E02EF2C7C7/code/QAnything-v1.2.0/QAnything$ docker ps
CONTAINER ID   IMAGE                                      COMMAND                   CREATED          STATUS                            PORTS                                                                                  NAMES
bbed7ba72522   freeren/qanything:v1.2.1                   "/opt/nvidia/nvidia_…"   9 seconds ago    Up 2 seconds                      0.0.0.0:5052->5052/tcp, :::5052->5052/tcp, 0.0.0.0:8777->8777/tcp, :::8777->8777/tcp   qanything-container-local
b66404734146   milvusdb/milvus:v2.3.4                     "/tini -- milvus run…"   11 seconds ago   Up 5 seconds (health: starting)                                                                                          milvus-standalone-local
5d1600492a32   mysql                                      "docker-entrypoint.s…"   13 seconds ago   Up 6 seconds                      3306/tcp, 33060/tcp                                                                    mysql-container-local
db9348b8b595   quay.io/coreos/etcd:v3.5.5                 "etcd -advertise-cli…"   13 seconds ago   Up 6 seconds (health: starting)   2379-2380/tcp                                                                          milvus-etcd-local
756b7264fe7a   minio/minio:RELEASE.2023-03-20T20-16-18Z   "/usr/bin/docker-ent…"   13 seconds ago   Up 6 seconds (health: starting)   9000/tcp                                                                               milvus-minio-local
(base) lihuan@Leon:/media/462EF2E02EF2C7C7/code/QAnything-v1.2.0/QAnything$ docker ps
CONTAINER ID   IMAGE                                      COMMAND                   CREATED          STATUS                             PORTS                                                                                  NAMES
bbed7ba72522   freeren/qanything:v1.2.1                   "/opt/nvidia/nvidia_…"   19 seconds ago   Up 12 seconds                      0.0.0.0:5052->5052/tcp, :::5052->5052/tcp, 0.0.0.0:8777->8777/tcp, :::8777->8777/tcp   qanything-container-local
b66404734146   milvusdb/milvus:v2.3.4                     "/tini -- milvus run…"   21 seconds ago   Up 15 seconds (health: starting)                                                                                          milvus-standalone-local
db9348b8b595   quay.io/coreos/etcd:v3.5.5                 "etcd -advertise-cli…"   23 seconds ago   Up 16 seconds (health: starting)   2379-2380/tcp                                                                          milvus-etcd-local
756b7264fe7a   minio/minio:RELEASE.2023-03-20T20-16-18Z   "/usr/bin/docker-ent…"   23 seconds ago   Up 16 seconds (health: starting)   9000/tcp                                                                               milvus-minio-local
(base) lihuan@Leon:/media/462EF2E02EF2C7C7/code/QAnything-v1.2.0/QAnything$ docker ps
CONTAINER ID   IMAGE                                      COMMAND                   CREATED          STATUS                             PORTS                                                                                  NAMES
bbed7ba72522   freeren/qanything:v1.2.1                   "/opt/nvidia/nvidia_…"   24 seconds ago   Up 17 seconds                      0.0.0.0:5052->5052/tcp, :::5052->5052/tcp, 0.0.0.0:8777->8777/tcp, :::8777->8777/tcp   qanything-container-local
b66404734146   milvusdb/milvus:v2.3.4                     "/tini -- milvus run…"   26 seconds ago   Up 20 seconds (health: starting)                                                                                          milvus-standalone-local
db9348b8b595   quay.io/coreos/etcd:v3.5.5                 "etcd -advertise-cli…"   28 seconds ago   Up 21 seconds (health: starting)   2379-2380/tcp                                                                          milvus-etcd-local
756b7264fe7a   minio/minio:RELEASE.2023-03-20T20-16-18Z   "/usr/bin/docker-ent…"   28 seconds ago   Up 21 seconds (health: starting)   9000/tcp                                                                               milvus-minio-local
(base) lihuan@Leon:/media/462EF2E02EF2C7C7/code/QAnything-v1.2.0/QAnything$ docker images
REPOSITORY            TAG                            IMAGE ID       CREATED         SIZE

### sanic_api.log

UPLOAD_ROOT_PATH: /workspace/qanything_local/QANY_DB/content
llm_api_serve_port: 7802
rerank_port: 9001
embed_port: 9001
<Logger debug_logger (INFO)> <Logger qa_logger (INFO)>
INFO:root:OPENAI_API_BASE = None
INFO:root:OPENAI_API_MODEL_NAME = None
[2024-03-01 09:42:34 +0800] [172] [INFO] Sanic v23.6.0
INFO:sanic.root:Sanic v23.6.0
[2024-03-01 09:42:34 +0800] [172] [INFO] Goin' Fast @ http://0.0.0.0:8777
INFO:sanic.root:Goin' Fast @ http://0.0.0.0:8777
[2024-03-01 09:42:34 +0800] [172] [INFO] mode: production, w/ 10 workers
INFO:sanic.root:mode: production, w/ 10 workers
[2024-03-01 09:42:34 +0800] [172] [INFO] server: sanic, HTTP/1.1
INFO:sanic.root:server: sanic, HTTP/1.1
[2024-03-01 09:42:34 +0800] [172] [INFO] python: 3.10.12
INFO:sanic.root:python: 3.10.12
[2024-03-01 09:42:34 +0800] [172] [INFO] platform: Linux-6.2.0-39-generic-x86_64-with-glibc2.35
INFO:sanic.root:platform: Linux-6.2.0-39-generic-x86_64-with-glibc2.35
[2024-03-01 09:42:34 +0800] [172] [INFO] packages: sanic-routing==23.12.0, sanic-ext==23.6.0
INFO:sanic.root:packages: sanic-routing==23.12.0, sanic-ext==23.6.0
INFO:root:OPENAI_API_BASE = None
INFO:root:OPENAI_API_MODEL_NAME = None
INFO:root:OPENAI_API_BASE = None
INFO:root:OPENAI_API_MODEL_NAME = None
INFO:root:OPENAI_API_BASE = None
INFO:root:OPENAI_API_BASE = None
INFO:root:OPENAI_API_MODEL_NAME = None
INFO:root:OPENAI_API_MODEL_NAME = None
UPLOAD_ROOT_PATH: /workspace/qanything_local/QANY_DB/content
llm_api_serve_port: 7802
rerank_port: 9001
embed_port: 9001
<Logger debug_logger (INFO)> <Logger qa_logger (INFO)>
[2024-03-01 09:42:40 +0800] [1021] [INFO] Sanic Extensions:
INFO:sanic.root:Sanic Extensions:
[2024-03-01 09:42:40 +0800] [1021] [INFO]   > injection [0 dependencies; 0 constants]
INFO:sanic.root:  > injection [0 dependencies; 0 constants]
[2024-03-01 09:42:40 +0800] [1021] [INFO]   > openapi [http://0.0.0.0:8777/docs]
INFO:sanic.root:  > openapi [http://0.0.0.0:8777/docs]
[2024-03-01 09:42:40 +0800] [1021] [INFO]   > http 
INFO:sanic.root:  > http 
[2024-03-01 09:42:40 +0800] [1021] [INFO]   > templating [jinja2==3.1.3]
INFO:sanic.root:  > templating [jinja2==3.1.3]
INFO:root:OPENAI_API_BASE = None
INFO:root:OPENAI_API_MODEL_NAME = None
[2024-03-01 09:42:40 +0800] [1021] [ERROR] 2005 (HY000): Unknown MySQL server host 'mysql-container-local' (-3)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/mysql/connector/connection_cext.py", line 308, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
_mysql_connector.MySQLInterfaceError: Unknown MySQL server host 'mysql-container-local' (-3)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sanic/worker/serve.py", line 117, in worker_serve
    return _serve_http_1(
  File "/usr/local/lib/python3.10/dist-packages/sanic/server/runners.py", line 223, in _serve_http_1
    loop.run_until_complete(app._server_event("init", "before"))
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.10/dist-packages/sanic/app.py", line 1764, in _server_event
    await self.dispatch(
  File "/usr/local/lib/python3.10/dist-packages/sanic/signals.py", line 208, in dispatch
    return await dispatch
  File "/usr/local/lib/python3.10/dist-packages/sanic/signals.py", line 183, in _dispatch
    raise e
  File "/usr/local/lib/python3.10/dist-packages/sanic/signals.py", line 167, in _dispatch
    retval = await maybe_coroutine
  File "/usr/local/lib/python3.10/dist-packages/sanic/app.py", line 1315, in _listener
    await maybe_coro
  File "/workspace/qanything_local/qanything_kernel/qanything_server/sanic_api.py", line 71, in init_local_doc_qa
    local_doc_qa.init_cfg(mode=args.mode)
  File "/workspace/qanything_local/qanything_kernel/core/local_doc_qa.py", line 54, in init_cfg
    self.milvus_summary = KnowledgeBaseManager(self.mode)
  File "/workspace/qanything_local/qanything_kernel/connector/database/mysql/mysql_client.py", line 18, in __init__
    self.check_database_(host, port, user, password, database)
  File "/workspace/qanything_local/qanything_kernel/connector/database/mysql/mysql_client.py", line 32, in check_database_
    cnx = mysql.connector.connect(
  File "/usr/local/lib/python3.10/dist-packages/mysql/connector/pooling.py", line 293, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/mysql/connector/connection_cext.py", line 129, in __init__
    self.connect(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/mysql/connector/abstracts.py", line 1237, in connect
    self._open_connection()
  File "/usr/local/lib/python3.10/dist-packages/mysql/connector/connection_cext.py", line 313, in _open_connection
    raise get_mysql_exception(
mysql.connector.errors.DatabaseError: 2005 (HY000): Unknown MySQL server host 'mysql-container-local' (-3)
ERROR:sanic.error:2005 (HY000): Unknown MySQL server host 'mysql-container-local' (-3)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/mysql/connector/connection_cext.py", line 308, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
_mysql_connector.MySQLInterfaceError: Unknown MySQL server host 'mysql-container-local' (-3)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sanic/worker/serve.py", line 117, in worker_serve
    return _serve_http_1(
  File "/usr/local/lib/python3.10/dist-packages/sanic/server/runners.py", line 223, in _serve_http_1
    loop.run_until_complete(app._server_event("init", "before"))
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.10/dist-packages/sanic/app.py", line 1764, in _server_event
    await self.dispatch(
  File "/usr/local/lib/python3.10/dist-packages/sanic/signals.py", line 208, in dispatch
    return await dispatch
  File "/usr/local/lib/python3.10/dist-packages/sanic/signals.py", line 183, in _dispatch
    raise e
  File "/usr/local/lib/python3.10/dist-packages/sanic/signals.py", line 167, in _dispatch
    retval = await maybe_coroutine
  File "/usr/local/lib/python3.10/dist-packages/sanic/app.py", line 1315, in _listener
    await maybe_coro
  File "/workspace/qanything_local/qanything_kernel/qanything_server/sanic_api.py", line 71, in init_local_doc_qa
    local_doc_qa.init_cfg(mode=args.mode)
  File "/workspace/qanything_local/qanything_kernel/core/local_doc_qa.py", line 54, in init_cfg
    self.milvus_summary = KnowledgeBaseManager(self.mode)
  File "/workspace/qanything_local/qanything_kernel/connector/database/mysql/mysql_client.py", line 18, in __init__
    self.check_database_(host, port, user, password, database)
  File "/workspace/qanything_local/qanything_kernel/connector/database/mysql/mysql_client.py", line 32, in check_database_
    cnx = mysql.connector.connect(
  File "/usr/local/lib/python3.10/dist-packages/mysql/connector/pooling.py", line 293, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/mysql/connector/connection_cext.py", line 129, in __init__
    self.connect(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/mysql/connector/abstracts.py", line 1237, in connect
    self._open_connection()
  File "/usr/local/lib/python3.10/dist-packages/mysql/connector/connection_cext.py", line 313, in _open_connection
    raise get_mysql_exception(
mysql.connector.errors.DatabaseError: 2005 (HY000): Unknown MySQL server host 'mysql-container-local' (-3)
[2024-03-01 09:42:40 +0800] [172] [ERROR] Not all workers acknowledged a successful startup. Shutting down.

One of your worker processes terminated before startup was completed. Please solve any errors experienced during startup. If you do not see an exception traceback in your error logs, try running Sanic in in a single process using --single-process or single_process=True. Once you are confident that the server is able to start without errors you can switch back to multiprocess mode.
ERROR:sanic.error:Not all workers acknowledged a successful startup. Shutting down.

One of your worker processes terminated before startup was completed. Please solve any errors experienced during startup. If you do not see an exception traceback in your error logs, try running Sanic in in a single process using --single-process or single_process=True. Once you are confident that the server is able to start without errors you can switch back to multiprocess mode.
[2024-03-01 09:42:40 +0800] [172] [INFO] Killing Sanic-Server-0-0 [1019]
INFO:sanic.root:Killing Sanic-Server-0-0 [1019]
[2024-03-01 09:42:40 +0800] [172] [INFO] Killing Sanic-Server-1-0 [1020]
INFO:sanic.root:Killing Sanic-Server-1-0 [1020]
[2024-03-01 09:42:40 +0800] [172] [INFO] Killing Sanic-Server-2-0 [1021]
INFO:sanic.root:Killing Sanic-Server-2-0 [1021]
[2024-03-01 09:42:40 +0800] [172] [INFO] Killing Sanic-Server-3-0 [1022]
INFO:sanic.root:Killing Sanic-Server-3-0 [1022]
[2024-03-01 09:42:40 +0800] [172] [INFO] Killing Sanic-Server-4-0 [1023]
UPLOAD_ROOT_PATH: /workspace/qanything_local/QANY_DB/content
llm_api_serve_port: 7802
rerank_port: 9001
embed_port: 9001
<Logger debug_logger (INFO)> <Logger qa_logger (INFO)>
[2024-03-01 09:42:40 +0800] [1028] [INFO] Sanic Extensions:
INFO:sanic.root:Killing Sanic-Server-4-0 [1023]
INFO:sanic.root:Sanic Extensions:
[2024-03-01 09:42:40 +0800] [1028] [INFO]   > injection [0 dependencies; 0 constants]
[2024-03-01 09:42:40 +0800] [172] [INFO] Killing Sanic-Server-5-0 [1024]
INFO:sanic.root:  > injection [0 dependencies; 0 constants]
INFO:sanic.root:Killing Sanic-Server-5-0 [1024]
[2024-03-01 09:42:40 +0800] [1028] [INFO]   > openapi [http://0.0.0.0:8777/docs]
[2024-03-01 09:42:40 +0800] [172] [INFO] Killing Sanic-Server-6-0 [1025]
INFO:sanic.root:  > openapi [http://0.0.0.0:8777/docs]
INFO:sanic.root:Killing Sanic-Server-6-0 [1025]
[2024-03-01 09:42:40 +0800] [1028] [INFO]   > http 
UPLOAD_ROOT_PATH: /workspace/qanything_local/QANY_DB/content
llm_api_serve_port: 7802
rerank_port: 9001
embed_port: 9001
<Logger debug_logger (INFO)> <Logger qa_logger (INFO)>
[2024-03-01 09:42:40 +0800] [1027] [INFO] Sanic Extensions:
[2024-03-01 09:42:40 +0800] [172] [INFO] Killing Sanic-Server-7-0 [1026]
INFO:sanic.root:  > http 
INFO:sanic.root:Sanic Extensions:
INFO:sanic.root:Killing Sanic-Server-7-0 [1026]
[2024-03-01 09:42:40 +0800] [1028] [INFO]   > templating [jinja2==3.1.3]
[2024-03-01 09:42:40 +0800] [1027] [INFO]   > injection [0 dependencies; 0 constants]
[2024-03-01 09:42:40 +0800] [172] [INFO] Killing Sanic-Server-8-0 [1027]
INFO:sanic.root:  > templating [jinja2==3.1.3]
INFO:sanic.root:  > injection [0 dependencies; 0 constants]
INFO:sanic.root:Killing Sanic-Server-8-0 [1027]
[2024-03-01 09:42:40 +0800] [1027] [INFO]   > openapi [http://0.0.0.0:8777/docs]
[2024-03-01 09:42:40 +0800] [172] [INFO] Killing Sanic-Server-9-0 [1028]
INFO:sanic.root:Killing Sanic-Server-9-0 [1028]
[2024-03-01 09:42:40 +0800] [172] [INFO] Server Stopped
INFO:sanic.root:Server Stopped
UPLOAD_ROOT_PATH: /workspace/qanything_local/QANY_DB/content
llm_api_serve_port: 7802
rerank_port: 9001
embed_port: 9001
<Logger debug_logger (INFO)> <Logger qa_logger (INFO)>

### 运行环境 | Environment

```Markdown
- OS:
- NVIDIA Driver:
- CUDA:
- Docker Compose:
- NVIDIA GPU Memory:
```

### QAnything日志 | QAnything logs

UPLOAD_ROOT_PATH: /workspace/qanything_local/QANY_DB/content
llm_api_serve_port: 7802
rerank_port: 9001
embed_port: 9001
<Logger debug_logger (INFO)> <Logger qa_logger (INFO)>
INFO:root:OPENAI_API_BASE = None
INFO:root:OPENAI_API_MODEL_NAME = None
[2024-03-01 09:42:34 +0800] [172] [INFO] Sanic v23.6.0
INFO:sanic.root:Sanic v23.6.0
[2024-03-01 09:42:34 +0800] [172] [INFO] Goin' Fast @ http://0.0.0.0:8777
INFO:sanic.root:Goin' Fast @ http://0.0.0.0:8777
[2024-03-01 09:42:34 +0800] [172] [INFO] mode: production, w/ 10 workers
INFO:sanic.root:mode: production, w/ 10 workers
[2024-03-01 09:42:34 +0800] [172] [INFO] server: sanic, HTTP/1.1
INFO:sanic.root:server: sanic, HTTP/1.1
[2024-03-01 09:42:34 +0800] [172] [INFO] python: 3.10.12
INFO:sanic.root:python: 3.10.12
[2024-03-01 09:42:34 +0800] [172] [INFO] platform: Linux-6.2.0-39-generic-x86_64-with-glibc2.35
INFO:sanic.root:platform: Linux-6.2.0-39-generic-x86_64-with-glibc2.35
[2024-03-01 09:42:34 +0800] [172] [INFO] packages: sanic-routing==23.12.0, sanic-ext==23.6.0
INFO:sanic.root:packages: sanic-routing==23.12.0, sanic-ext==23.6.0
INFO:root:OPENAI_API_BASE = None
INFO:root:OPENAI_API_MODEL_NAME = None
INFO:root:OPENAI_API_BASE = None
INFO:root:OPENAI_API_MODEL_NAME = None
INFO:root:OPENAI_API_BASE = None
INFO:root:OPENAI_API_BASE = None
INFO:root:OPENAI_API_MODEL_NAME = None
INFO:root:OPENAI_API_MODEL_NAME = None
UPLOAD_ROOT_PATH: /workspace/qanything_local/QANY_DB/content
llm_api_serve_port: 7802
rerank_port: 9001
embed_port: 9001
<Logger debug_logger (INFO)> <Logger qa_logger (INFO)>
[2024-03-01 09:42:40 +0800] [1021] [INFO] Sanic Extensions:
INFO:sanic.root:Sanic Extensions:
[2024-03-01 09:42:40 +0800] [1021] [INFO]   > injection [0 dependencies; 0 constants]
INFO:sanic.root:  > injection [0 dependencies; 0 constants]
[2024-03-01 09:42:40 +0800] [1021] [INFO]   > openapi [http://0.0.0.0:8777/docs]
INFO:sanic.root:  > openapi [http://0.0.0.0:8777/docs]
[2024-03-01 09:42:40 +0800] [1021] [INFO]   > http 
INFO:sanic.root:  > http 
[2024-03-01 09:42:40 +0800] [1021] [INFO]   > templating [jinja2==3.1.3]
INFO:sanic.root:  > templating [jinja2==3.1.3]
INFO:root:OPENAI_API_BASE = None
INFO:root:OPENAI_API_MODEL_NAME = None
[2024-03-01 09:42:40 +0800] [1021] [ERROR] 2005 (HY000): Unknown MySQL server host 'mysql-container-local' (-3)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/mysql/connector/connection_cext.py", line 308, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
_mysql_connector.MySQLInterfaceError: Unknown MySQL server host 'mysql-container-local' (-3)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sanic/worker/serve.py", line 117, in worker_serve
    return _serve_http_1(
  File "/usr/local/lib/python3.10/dist-packages/sanic/server/runners.py", line 223, in _serve_http_1
    loop.run_until_complete(app._server_event("init", "before"))
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.10/dist-packages/sanic/app.py", line 1764, in _server_event
    await self.dispatch(
  File "/usr/local/lib/python3.10/dist-packages/sanic/signals.py", line 208, in dispatch
    return await dispatch
  File "/usr/local/lib/python3.10/dist-packages/sanic/signals.py", line 183, in _dispatch
    raise e
  File "/usr/local/lib/python3.10/dist-packages/sanic/signals.py", line 167, in _dispatch
    retval = await maybe_coroutine
  File "/usr/local/lib/python3.10/dist-packages/sanic/app.py", line 1315, in _listener
    await maybe_coro
  File "/workspace/qanything_local/qanything_kernel/qanything_server/sanic_api.py", line 71, in init_local_doc_qa
    local_doc_qa.init_cfg(mode=args.mode)
  File "/workspace/qanything_local/qanything_kernel/core/local_doc_qa.py", line 54, in init_cfg
    self.milvus_summary = KnowledgeBaseManager(self.mode)
  File "/workspace/qanything_local/qanything_kernel/connector/database/mysql/mysql_client.py", line 18, in __init__
    self.check_database_(host, port, user, password, database)
  File "/workspace/qanything_local/qanything_kernel/connector/database/mysql/mysql_client.py", line 32, in check_database_
    cnx = mysql.connector.connect(
  File "/usr/local/lib/python3.10/dist-packages/mysql/connector/pooling.py", line 293, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/mysql/connector/connection_cext.py", line 129, in __init__
    self.connect(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/mysql/connector/abstracts.py", line 1237, in connect
    self._open_connection()
  File "/usr/local/lib/python3.10/dist-packages/mysql/connector/connection_cext.py", line 313, in _open_connection
    raise get_mysql_exception(
mysql.connector.errors.DatabaseError: 2005 (HY000): Unknown MySQL server host 'mysql-container-local' (-3)
ERROR:sanic.error:2005 (HY000): Unknown MySQL server host 'mysql-container-local' (-3)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/mysql/connector/connection_cext.py", line 308, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
_mysql_connector.MySQLInterfaceError: Unknown MySQL server host 'mysql-container-local' (-3)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sanic/worker/serve.py", line 117, in worker_serve
    return _serve_http_1(
  File "/usr/local/lib/python3.10/dist-packages/sanic/server/runners.py", line 223, in _serve_http_1
    loop.run_until_complete(app._server_event("init", "before"))
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.10/dist-packages/sanic/app.py", line 1764, in _server_event
    await self.dispatch(
  File "/usr/local/lib/python3.10/dist-packages/sanic/signals.py", line 208, in dispatch
    return await dispatch
  File "/usr/local/lib/python3.10/dist-packages/sanic/signals.py", line 183, in _dispatch
    raise e
  File "/usr/local/lib/python3.10/dist-packages/sanic/signals.py", line 167, in _dispatch
    retval = await maybe_coroutine
  File "/usr/local/lib/python3.10/dist-packages/sanic/app.py", line 1315, in _listener
    await maybe_coro
  File "/workspace/qanything_local/qanything_kernel/qanything_server/sanic_api.py", line 71, in init_local_doc_qa
    local_doc_qa.init_cfg(mode=args.mode)
  File "/workspace/qanything_local/qanything_kernel/core/local_doc_qa.py", line 54, in init_cfg
    self.milvus_summary = KnowledgeBaseManager(self.mode)
  File "/workspace/qanything_local/qanything_kernel/connector/database/mysql/mysql_client.py", line 18, in __init__
    self.check_database_(host, port, user, password, database)
  File "/workspace/qanything_local/qanything_kernel/connector/database/mysql/mysql_client.py", line 32, in check_database_
    cnx = mysql.connector.connect(
  File "/usr/local/lib/python3.10/dist-packages/mysql/connector/pooling.py", line 293, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/mysql/connector/connection_cext.py", line 129, in __init__
    self.connect(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/mysql/connector/abstracts.py", line 1237, in connect
    self._open_connection()
  File "/usr/local/lib/python3.10/dist-packages/mysql/connector/connection_cext.py", line 313, in _open_connection
    raise get_mysql_exception(
mysql.connector.errors.DatabaseError: 2005 (HY000): Unknown MySQL server host 'mysql-container-local' (-3)
[2024-03-01 09:42:40 +0800] [172] [ERROR] Not all workers acknowledged a successful startup. Shutting down.

One of your worker processes terminated before startup was completed. Please solve any errors experienced during startup. If you do not see an exception traceback in your error logs, try running Sanic in in a single process using --single-process or single_process=True. Once you are confident that the server is able to start without errors you can switch back to multiprocess mode.
ERROR:sanic.error:Not all workers acknowledged a successful startup. Shutting down.

One of your worker processes terminated before startup was completed. Please solve any errors experienced during startup. If you do not see an exception traceback in your error logs, try running Sanic in in a single process using --single-process or single_process=True. Once you are confident that the server is able to start without errors you can switch back to multiprocess mode.
[2024-03-01 09:42:40 +0800] [172] [INFO] Killing Sanic-Server-0-0 [1019]
INFO:sanic.root:Killing Sanic-Server-0-0 [1019]
[2024-03-01 09:42:40 +0800] [172] [INFO] Killing Sanic-Server-1-0 [1020]
INFO:sanic.root:Killing Sanic-Server-1-0 [1020]
[2024-03-01 09:42:40 +0800] [172] [INFO] Killing Sanic-Server-2-0 [1021]
INFO:sanic.root:Killing Sanic-Server-2-0 [1021]
[2024-03-01 09:42:40 +0800] [172] [INFO] Killing Sanic-Server-3-0 [1022]
INFO:sanic.root:Killing Sanic-Server-3-0 [1022]
[2024-03-01 09:42:40 +0800] [172] [INFO] Killing Sanic-Server-4-0 [1023]
UPLOAD_ROOT_PATH: /workspace/qanything_local/QANY_DB/content
llm_api_serve_port: 7802
rerank_port: 9001
embed_port: 9001
<Logger debug_logger (INFO)> <Logger qa_logger (INFO)>
[2024-03-01 09:42:40 +0800] [1028] [INFO] Sanic Extensions:
INFO:sanic.root:Killing Sanic-Server-4-0 [1023]
INFO:sanic.root:Sanic Extensions:
[2024-03-01 09:42:40 +0800] [1028] [INFO]   > injection [0 dependencies; 0 constants]
[2024-03-01 09:42:40 +0800] [172] [INFO] Killing Sanic-Server-5-0 [1024]
INFO:sanic.root:  > injection [0 dependencies; 0 constants]
INFO:sanic.root:Killing Sanic-Server-5-0 [1024]
[2024-03-01 09:42:40 +0800] [1028] [INFO]   > openapi [http://0.0.0.0:8777/docs]
[2024-03-01 09:42:40 +0800] [172] [INFO] Killing Sanic-Server-6-0 [1025]
INFO:sanic.root:  > openapi [http://0.0.0.0:8777/docs]
INFO:sanic.root:Killing Sanic-Server-6-0 [1025]
[2024-03-01 09:42:40 +0800] [1028] [INFO]   > http 
UPLOAD_ROOT_PATH: /workspace/qanything_local/QANY_DB/content
llm_api_serve_port: 7802
rerank_port: 9001
embed_port: 9001
<Logger debug_logger (INFO)> <Logger qa_logger (INFO)>
[2024-03-01 09:42:40 +0800] [1027] [INFO] Sanic Extensions:
[2024-03-01 09:42:40 +0800] [172] [INFO] Killing Sanic-Server-7-0 [1026]
INFO:sanic.root:  > http 
INFO:sanic.root:Sanic Extensions:
INFO:sanic.root:Killing Sanic-Server-7-0 [1026]
[2024-03-01 09:42:40 +0800] [1028] [INFO]   > templating [jinja2==3.1.3]
[2024-03-01 09:42:40 +0800] [1027] [INFO]   > injection [0 dependencies; 0 constants]
[2024-03-01 09:42:40 +0800] [172] [INFO] Killing Sanic-Server-8-0 [1027]
INFO:sanic.root:  > templating [jinja2==3.1.3]
INFO:sanic.root:  > injection [0 dependencies; 0 constants]
INFO:sanic.root:Killing Sanic-Server-8-0 [1027]
[2024-03-01 09:42:40 +0800] [1027] [INFO]   > openapi [http://0.0.0.0:8777/docs]
[2024-03-01 09:42:40 +0800] [172] [INFO] Killing Sanic-Server-9-0 [1028]
INFO:sanic.root:Killing Sanic-Server-9-0 [1028]
[2024-03-01 09:42:40 +0800] [172] [INFO] Server Stopped
INFO:sanic.root:Server Stopped
UPLOAD_ROOT_PATH: /workspace/qanything_local/QANY_DB/content
llm_api_serve_port: 7802
rerank_port: 9001
embed_port: 9001
<Logger debug_logger (INFO)> <Logger qa_logger (INFO)>

**Comment by zlh1992** [comment]
I just meet same problem. Did you solved it?

**Comment by yaleimeng** [comment]
我也是同样问题，怎么解决？

**Comment by simonqian** [comment]
我也遇到同样的问题

**Comment by hwwzyh** [comment]
删除mysql的镜像，重新pull，然后启动成功了
