### ISSUE TITLE
[BUG] 服务启动成功，页面可访问，但无法上传文档进行解析

### ISSUE THREAD

**Issue by wingerx** [netease-youdao/QAnything#18]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

上传文档进行解析，页面显示情况如下图：
![image](https://github.com/netease-youdao/QAnything/assets/33280738/143a9859-b3e1-47bf-a807-ba7da465db26)

### 期望行为 | Expected Behavior

可以正常分析文档

### 运行环境 | Environment

```Markdown
- OS:Ubuntu 22.04
- NVIDIA Driver: 535.146.02
- CUDA:12.2
- Docker Compose:
- NVIDIA GPU Memory: 8gb
```

### QAnything日志 | QAnything logs

```
2024-01-15 18:31:03,621 - root - INFO - kb_id: KB8b14e16f895044519023ea4c576e1ea1
2024-01-15 18:31:06,577 - root - INFO - upload_files zhujietest4
2024-01-15 18:31:06,578 - root - INFO - mode: strong
2024-01-15 18:31:06,578 - root - WARNING - missing use_local_file in request
2024-01-15 18:31:06,579 - root - INFO - check_kb_exist [('KB8b14e16f895044519023ea4c576e1ea1',)]
2024-01-15 18:31:06,579 - root - INFO - ori name: jira�~E~M置�~S~M�~\�~V~G档.docx
2024-01-15 18:31:06,579 - root - INFO - decode name: jira�~E~M置�~S~M�~\�~V~G档.docx
2024-01-15 18:31:06,579 - root - INFO - cleaned name: jira�~E~M置�~S~M�~\�~V~G档.docx
2024-01-15 18:31:06,579 - root - INFO - check_user_exist [('zhujietest4',)]
2024-01-15 18:31:06,580 - root - INFO - check_kb_exist [('KB8b14e16f895044519023ea4c576e1ea1',)]
2024-01-15 18:31:06,599 - root - INFO - jira�~E~M置�~S~M�~\�~V~G档.docx, 9c10e7b1980d4c9f862859cc71c87661, success
2024-01-15 18:31:06,601 - root - INFO - success init localfile jira�~E~M置�~S~M�~\�~V~G档.docx
2024-01-15 18:31:06,604 - root - INFO - insert_files_to_milvus: KB8b14e16f895044519023ea4c576e1ea1
2024-01-15 18:31:06,604 - root - INFO - match milvus_client: <qanything_kernel.connector.database.milvus.milvus_client.MilvusClient object at 0x7fb13488fe50>
2024-01-15 18:31:06,643 - root - INFO - langchain analysis content head: �~[��~U�~Z
2024-01-15 18:31:06,646 - root - INFO - split time: 0.03937077522277832 54
2024-01-15 18:31:06,651 - root - ERROR - embedding error: Traceback (most recent call last):
  File "/workspace/qanything_local/qanything_kernel/core/local_doc_qa.py", line 114, in insert_files_to_milvus
    local_file.create_embedding()
  File "/workspace/qanything_local/qanything_kernel/core/local_file.py", line 107, in create_embedding
    self.embs = self.emb_infer._get_len_safe_embeddings([doc.page_content for doc in self.docs])
  File "/workspace/qanything_local/qanything_kernel/connector/embedding/embedding_for_local.py", line 33, in _get_len_safe_embeddings
    embeddings = future.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/workspace/qanything_local/qanything_kernel/connector/embedding/embedding_for_local.py", line 20, in _get_embedding
    embeddings = embedding_client.get_embedding(queries)
  File "/workspace/qanything_local/qanything_kernel/connector/embedding/embedding_client.py", line 45, in get_embedding
    model_config = client.get_model_config(self._model_name, self._model_version)
  File "/usr/local/lib/python3.10/dist-packages/tritonclient/grpc/__init__.py", line 590, in get_model_config
    raise_error_grpc(rpc_error)
  File "/usr/local/lib/python3.10/dist-packages/tritonclient/grpc/__init__.py", line 76, in raise_error_grpc
    raise get_error_grpc(rpc_error) from None
tritonclient.utils.InferenceServerException: [StatusCode.NOT_FOUND] Request for unknown model: 'embed' is not found

2024-01-15 18:31:06,654 - root - INFO - insert_to_milvus: success num: 0, failed num: 1
2024-01-15 18:31:07,371 - root - INFO - list_docs zhujietest4
2024-01-15 18:31:07,371 - root - INFO - kb_id: KB8b14e16f895044519023ea4c576e1ea1
2024-01-15 18:31:07,372 - root - INFO - list_docs zhujietest4
```

**Comment by bankxi** [comment]
same problem, how to resolve?

**Comment by dhjing** [comment]
I have the same problem. Have you solved it?

**Comment by shu1ao2han3** [comment]
有同样的问题，不知道怎么解决
