### ISSUE TITLE
[BUG] [sanic_api.log] : ValueError: invalid literal for int() with base 10: 'None'

### ISSUE THREAD

**Issue by 62bit** [netease-youdao/QAnything#197]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

启动不起来55555555，各位佬帮忙看一下怎么解决
---------------
启动命令：bash ./run.sh -c local -i 0 -b hf -m Qwen-7B-QAnything -t qwen-7b-qanything
```
fatal: not a git repository (or any parent up to mount point /mnt/wsl/docker-desktop-bind-mounts/Ubuntu)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /mnt/wsl/docker-desktop-bind-mounts/Ubuntu)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /mnt/wsl/docker-desktop-bind-mounts/Ubuntu)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
====================================================
******************** 重要提示 ********************
====================================================

检测到master分支有新的代码更新，如需体验最新的功能，可以手动执行 git pull 来同步最新的代码。

model_size=7B
sed: cannot rename ./sedn9Yj5Q: Permission denied
GPUID1=0, GPUID2=0, device_id=0
sed: cannot rename ./sedGljkfs: Permission denied
sed: cannot rename ./sedVPdMtJ: Permission denied
llm_api is set to [local]
device_id is set to [0]
runtime_backend is set to [default]
model_name is set to []
conv_template is set to []
tensor_parallel is set to [1]
gpu_memory_utilization is set to [0.81]
sed: cannot rename ./sedBHkB6p: Permission denied
sed: cannot rename ./sedmELT8O: Permission denied
sed: cannot rename ./sedjOrfIJ: Permission denied
sed: cannot rename ./sednaKSu7: Permission denied
sed: cannot rename ./sedLUPHww: Permission denied
sed: cannot rename ./sedJcggOO: Permission denied
sed: cannot rename ./sedo54ZvZ: Permission denied
Do you want to use the previous ip: localhost? (yes/no) 是否使用上次的ip: ？(yes/no) 回车默认选yes，请输入:yes
Running under WSL
请输入Windows版本（WIN11/WIN10）回车默认选WIN11，请输入：WIN10
./run.sh: line 15: .env: Permission denied
 Container qanything-container-local  Stopping
 Container qanything-container-local  Stopped
 Container qanything-container-local  Removing
 Container qanything-container-local  Removed
 Container mysql-container-local  Stopping
 Container milvus-standalone-local  Stopping
 Container milvus-standalone-local  Stopped
 Container milvus-standalone-local  Removing
 Container milvus-standalone-local  Removed
 Container milvus-etcd-local  Stopping
 Container milvus-minio-local  Stopping
 Container milvus-etcd-local  Stopped
 Container milvus-etcd-local  Removing
 Container milvus-minio-local  Stopped
 Container milvus-minio-local  Removing
 Container milvus-etcd-local  Removed
 Container milvus-minio-local  Removed
 Container mysql-container-local  Stopped
 Container mysql-container-local  Removing
 Container mysql-container-local  Removed
 Network qanything_milvus_mysql_local  Removing
 Network qanything_milvus_mysql_local  Removed
[+] Running 1/6
[+] Running 2/6thing_milvus_mysql_local  Created                                                                   1.4s
 ⠴ Network qanything_milvus_mysql_local  Created                                                                   1.5s
[+] Running 2/6ilvus-etcd-local           Started                                                                   1.4s
 ⠦ Network qanything_milvus_mysql_local  Created                                                                   1.6s
[+] Running 3/6ilvus-etcd-local           Started                                                                   1.4s
 ⠧ Network qanything_milvus_mysql_local  Created                                                                   1.7s
 ✔ Container milvus-etcd-local           Started                                                                   1.4s[+] Running 3/6ysql-container-local       Started                                                                   1.3s
 ⠇ Network qanything_milvus_mysql_local  Created                                                                   1.8s
 ✔ Container milvus-etcd-local           Started                                                                   1.4s[+] Running 3/6ysql-container-local       Started                                                                   1.3s
 ⠏ Network qanything_milvus_mysql_local  Created                                                                   1.9s
 ✔ Container milvus-etcd-local           Started                                                                   1.4s[+] Running 3/6ysql-container-local       Started                                                                   1.3s
 ⠋ Network qanything_milvus_mysql_local  Created                                                                   2.0s
 ✔ Container milvus-etcd-local           Started                                                                   1.4s[+] Running 3/6ysql-container-local       Started                                                                   1.3s
 ⠙ Network qanything_milvus_mysql_local  Created                                                                   2.1s
 ✔ Container milvus-etcd-local           Started                                                                   1.4s[+] Running 4/6ysql-container-local       Started                                                                   1.3s
 ⠹ Network qanything_milvus_mysql_local  Created                                                                   2.2s
 ✔ Container milvus-etcd-local           Started                                                                   1.4s ✔ Container mysql-container-local       Started                                                                   1.3s
[+] Running 4/6ilvus-minio-local          Started                                                                   1.6s
 ⠸ Network qanything_milvus_mysql_local  Created                                                                   2.3s
 ✔ Container milvus-etcd-local           Started                                                                   1.4s
[+] Running 4/6ilvus-minio-local          Started                                                                   1.6s
 ⠼ Network qanything_milvus_mysql_local  Created                                                                   2.4s
 ✔ Container milvus-etcd-local           Started                                                                   1.4s
[+] Running 4/6ilvus-minio-local          Started                                                                   1.6s
 ⠴ Network qanything_milvus_mysql_local  Created                                                                   2.5s
 ✔ Container milvus-etcd-local           Started                                                                   1.4s
[+] Running 4/6ilvus-minio-local          Started                                                                   1.6s
 ⠦ Network qanything_milvus_mysql_local  Created                                                                   2.6s
 ✔ Container milvus-etcd-local           Started                                                                   1.4s
[+] Running 4/6ilvus-minio-local          Started                                                                   1.6s
 ⠧ Network qanything_milvus_mysql_local  Created                                                                   2.7s
 ✔ Container milvus-etcd-local           Started                                                                   1.4s
[+] Running 4/6ilvus-minio-local          Started                                                                   1.6s
 ⠇ Network qanything_milvus_mysql_local  Created                                                                   2.8s
 ✔ Container milvus-etcd-local           Started                                                                   1.4s
[+] Running 4/6ilvus-minio-local          Started                                                                   1.6s
 ⠏ Network qanything_milvus_mysql_local  Created                                                                   2.9s
 ✔ Container milvus-etcd-local           Started                                                                   1.4s
[+] Running 5/6ilvus-minio-local          Started                                                                   1.6s
 ⠋ Network qanything_milvus_mysql_local  Created                                                                   3.0s
 ✔ Container milvus-etcd-local           Started                                                                   1.4s
 ✔ Container milvus-minio-local          Started                                                                   1.6s
 ✔ Container mysql-container-local       Started                                                                   1.3s
 ✔ Container milvus-standalone-local     Started                                                                   1.6s
 ✔ Container qanything-container-local   Started                                                                   2.4s
qanything-container-local  |
qanything-container-local  | =============================
qanything-container-local  | == Triton Inference Server ==
qanything-container-local  | =============================
qanything-container-local  |
qanything-container-local  | NVIDIA Release 23.05 (build 61161506)
qanything-container-local  | Triton Server Version 2.34.0
qanything-container-local  |
qanything-container-local  | Copyright (c) 2018-2023, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.
qanything-container-local  |
qanything-container-local  | Various files include modifications (c) NVIDIA CORPORATION & AFFILIATES.  All rights reserved.
qanything-container-local  |
qanything-container-local  | This container image and its contents are governed by the NVIDIA Deep Learning Container License.
qanything-container-local  | By pulling and using the container, you accept the terms and conditions of this license:
qanything-container-local  | https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license
qanything-container-local  |
qanything-container-local  | llm_api is set to [local]
qanything-container-local  | device_id is set to [0]
qanything-container-local  | runtime_backend is set to [hf]
qanything-container-local  | model_name is set to [Qwen-7B-QAnything]
qanything-container-local  | conv_template is set to [qwen-7b-qanything]
qanything-container-local  | tensor_parallel is set to [1]
qanything-container-local  | gpu_memory_utilization is set to [0.81]
qanything-container-local  | checksum 4397ac57e217628e8767c81eb79eceb9
qanything-container-local  | default_checksum 4397ac57e217628e8767c81eb79eceb9
qanything-container-local  |
qanything-container-local  | [notice] A new release of pip is available: 23.3.2 -> 24.0
qanything-container-local  | [notice] To update, run: python3 -m pip install --upgrade pip
qanything-container-local  | GPU ID: 0, 0
qanything-container-local  | GPU1 Model: NVIDIA RTX A4000
qanything-container-local  | Compute Capability: null
qanything-container-local  | OCR_USE_GPU=False because null < 7.5
qanything-container-local  | /workspace/qanything_local/scripts/run_for_local_option.sh: line 14: /workspace/qanything_local/.env: Permission denied
qanything-container-local  | ====================================================
qanything-container-local  | ******************** 重要提示 ********************
qanything-container-local  | ====================================================
qanything-container-local  |
qanything-container-local  | 您当前的显存为 16376 MiB 推荐部署小于等于7B的大模型
qanything-container-local  | 为了防止显存溢出，tokens上限默认设置为1400
qanything-container-local  | /workspace/qanything_local/scripts/run_for_local_option.sh: line 14: /workspace/qanything_local/.env: Permission denied
qanything-container-local  | The triton server for embedding and reranker will start on 0 GPUs
qanything-container-local  | /workspace/qanything_local/scripts/run_for_local_option.sh: line 14: /workspace/qanything_local/.env: Permission denied
qanything-container-local  | /workspace/qanything_local/scripts/run_for_local_option.sh: line 14: /workspace/qanything_local/.env: Permission denied
qanything-container-local  | /workspace/qanything_local/scripts/run_for_local_option.sh: line 14: /workspace/qanything_local/.env: Permission denied
qanything-container-local  | /workspace/qanything_local/scripts/run_for_local_option.sh: line 14: /workspace/qanything_local/.env: Permission denied
qanything-container-local  | /workspace/qanything_local/scripts/run_for_local_option.sh: line 14: /workspace/qanything_local/.env: Permission denied
qanything-container-local  | Executing hf runtime_backend
qanything-container-local  | The rerank service is ready! (2/8)
qanything-container-local  | rerank服务已就绪! (2/8)
qanything-container-local  | The ocr service is ready! (3/8)
qanything-container-local  | OCR服务已就绪! (3/8)
qanything-container-local  | Waiting for the backend service to start...
qanything-container-local  | 等待启动后端服务
qanything-container-local  | Waiting for the backend service to start...
qanything-container-local  | 等待启动后端服务
qanything-container-local  | Waiting for the backend service to start...
qanything-container-local  | 等待启动后端服务
qanything-container-local  | Waiting for the backend service to start...
qanything-container-local  | 等待启动后端服务
qanything-container-local  | Waiting for the backend service to start...
qanything-container-local  | 等待启动后端服务
qanything-container-local  | Waiting for the backend service to start...
qanything-container-local  | 等待启动后端服务
qanything-container-local  | Waiting for the backend service to start...
qanything-container-local  | 等待启动后端服务
qanything-container-local  | Waiting for the backend service to start...
qanything-container-local  | 等待启动后端服务
qanything-container-local  | Waiting for the backend service to start...
qanything-container-local  | 等待启动后端服务
qanything-container-local  | Waiting for the backend service to start...
qanything-container-local  | 等待启动后端服务
qanything-container-local  | Waiting for the backend service to start...
qanything-container-local  | 等待启动后端服务
qanything-container-local  | Waiting for the backend service to start...
qanything-container-local  | 等待启动后端服务
qanything-container-local  | Waiting for the backend service to start...
qanything-container-local  | 等待启动后端服务
qanything-container-local  | Waiting for the backend service to start...
qanything-container-local  | 等待启动后端服务
qanything-container-local  | Waiting for the backend service to start...
qanything-container-local  | 等待启动后端服务
qanything-container-local  | Waiting for the backend service to start...
qanything-container-local  | 等待启动后端服务
qanything-container-local  | Waiting for the backend service to start...
qanything-container-local  | 等待启动后端服务
qanything-container-local  | Waiting for the backend service to start...
qanything-container-local  | 等待启动后端服务
qanything-container-local  | Waiting for the backend service to start...
qanything-container-local  | 等待启动后端服务
qanything-container-local  | Waiting for the backend service to start...
qanything-container-local  | 等待启动后端服务
qanything-container-local  | Waiting for the backend service to start...
qanything-container-local  | 等待启动后端服务
qanything-container-local  | 启动后端服务超时，请检查日志文件 /workspace/qanything_local/logs/debug_logs/sanic_api.log  获取更多信息。
```
sanic_api.log
```
UPLOAD_ROOT_PATH: /workspace/qanything_local/QANY_DB/content
llm_api_serve_port: None
rerank_port: None
embed_port: None
<Logger debug_logger (INFO)> <Logger qa_logger (INFO)>
INFO:root:OPENAI_API_BASE = None
INFO:root:OPENAI_API_MODEL_NAME = None
[2024-03-23 10:46:57 +0800] [143] [INFO] Sanic v23.6.0
INFO:sanic.root:Sanic v23.6.0
[2024-03-23 10:46:57 +0800] [143] [INFO] Goin' Fast @ http://0.0.0.0:8777
INFO:sanic.root:Goin' Fast @ http://0.0.0.0:8777
[2024-03-23 10:46:57 +0800] [143] [INFO] mode: production, w/ 10 workers
INFO:sanic.root:mode: production, w/ 10 workers
[2024-03-23 10:46:57 +0800] [143] [INFO] server: sanic, HTTP/1.1
INFO:sanic.root:server: sanic, HTTP/1.1
[2024-03-23 10:46:57 +0800] [143] [INFO] python: 3.10.12
INFO:sanic.root:python: 3.10.12
[2024-03-23 10:46:57 +0800] [143] [INFO] platform: Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
INFO:sanic.root:platform: Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
[2024-03-23 10:46:57 +0800] [143] [INFO] packages: sanic-routing==23.12.0, sanic-ext==23.6.0
INFO:sanic.root:packages: sanic-routing==23.12.0, sanic-ext==23.6.0
INFO:root:OPENAI_API_BASE = None
INFO:root:OPENAI_API_MODEL_NAME = None
INFO:root:OPENAI_API_BASE = None
INFO:root:OPENAI_API_MODEL_NAME = None
INFO:root:OPENAI_API_BASE = None
INFO:root:OPENAI_API_MODEL_NAME = None
INFO:root:OPENAI_API_BASE = None
INFO:root:OPENAI_API_MODEL_NAME = None
UPLOAD_ROOT_PATH: /workspace/qanything_local/QANY_DB/content
llm_api_serve_port: None
rerank_port: None
embed_port: None
<Logger debug_logger (INFO)> <Logger qa_logger (INFO)>
[2024-03-23 10:47:23 +0800] [1124] [INFO] Sanic Extensions:
INFO:sanic.root:Sanic Extensions:
[2024-03-23 10:47:23 +0800] [1124] [INFO]   > injection [0 dependencies; 0 constants]
INFO:sanic.root:  > injection [0 dependencies; 0 constants]
[2024-03-23 10:47:23 +0800] [1124] [INFO]   > openapi [http://0.0.0.0:8777/docs]
INFO:sanic.root:  > openapi [http://0.0.0.0:8777/docs]
[2024-03-23 10:47:23 +0800] [1124] [INFO]   > http 
INFO:sanic.root:  > http 
[2024-03-23 10:47:23 +0800] [1124] [INFO]   > templating [jinja2==3.1.3]
INFO:sanic.root:  > templating [jinja2==3.1.3]
INFO:root:OPENAI_API_BASE = None
INFO:root:OPENAI_API_BASE = None
INFO:root:OPENAI_API_MODEL_NAME = None
INFO:root:OPENAI_API_BASE = None
INFO:root:OPENAI_API_MODEL_NAME = None
INFO:root:OPENAI_API_BASE = None
INFO:root:OPENAI_API_MODEL_NAME = None
INFO:root:OPENAI_API_MODEL_NAME = None
[2024-03-23 10:47:23 +0800] [1124] [ERROR] Invalid port: 'None'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/httpx/_urlparse.py", line 346, in normalize_port
    port_as_int = int(port)
ValueError: invalid literal for int() with base 10: 'None'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sanic/worker/serve.py", line 117, in worker_serve
    return _serve_http_1(
  File "/usr/local/lib/python3.10/dist-packages/sanic/server/runners.py", line 223, in _serve_http_1
    loop.run_until_complete(app._server_event("init", "before"))
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.10/dist-packages/sanic/app.py", line 1764, in _server_event
    await self.dispatch(
  File "/usr/local/lib/python3.10/dist-packages/sanic/signals.py", line 208, in dispatch
    return await dispatch
  File "/usr/local/lib/python3.10/dist-packages/sanic/signals.py", line 183, in _dispatch
    raise e
  File "/usr/local/lib/python3.10/dist-packages/sanic/signals.py", line 167, in _dispatch
    retval = await maybe_coroutine
  File "/usr/local/lib/python3.10/dist-packages/sanic/app.py", line 1315, in _listener
    await maybe_coro
  File "/workspace/qanything_local/qanything_kernel/qanything_server/sanic_api.py", line 71, in init_local_doc_qa
    local_doc_qa.init_cfg(mode=args.mode)
  File "/workspace/qanything_local/qanything_kernel/core/local_doc_qa.py", line 51, in init_cfg
    self.llm: ZiyueLLM = ZiyueLLM()
  File "/workspace/qanything_local/qanything_kernel/connector/llm/llm_for_fastchat.py", line 37, in __init__
    self.client = OpenAI(base_url=base_url, api_key="EMPTY")
  File "/usr/local/lib/python3.10/dist-packages/openai/_client.py", line 106, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 745, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 348, in __init__
    self._base_url = self._enforce_trailing_slash(URL(base_url))
  File "/usr/local/lib/python3.10/dist-packages/httpx/_urls.py", line 115, in __init__
    self._uri_reference = urlparse(url, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_urlparse.py", line 246, in urlparse
    parsed_port: typing.Optional[int] = normalize_port(port, scheme)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_urlparse.py", line 348, in normalize_port
    raise InvalidURL(f"Invalid port: {port!r}")
httpx.InvalidURL: Invalid port: 'None'
ERROR:sanic.error:Invalid port: 'None'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/httpx/_urlparse.py", line 346, in normalize_port
    port_as_int = int(port)
ValueError: invalid literal for int() with base 10: 'None'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sanic/worker/serve.py", line 117, in worker_serve
    return _serve_http_1(
  File "/usr/local/lib/python3.10/dist-packages/sanic/server/runners.py", line 223, in _serve_http_1
    loop.run_until_complete(app._server_event("init", "before"))
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.10/dist-packages/sanic/app.py", line 1764, in _server_event
    await self.dispatch(
  File "/usr/local/lib/python3.10/dist-packages/sanic/signals.py", line 208, in dispatch
    return await dispatch
  File "/usr/local/lib/python3.10/dist-packages/sanic/signals.py", line 183, in _dispatch
    raise e
  File "/usr/local/lib/python3.10/dist-packages/sanic/signals.py", line 167, in _dispatch
    retval = await maybe_coroutine
  File "/usr/local/lib/python3.10/dist-packages/sanic/app.py", line 1315, in _listener
    await maybe_coro
  File "/workspace/qanything_local/qanything_kernel/qanything_server/sanic_api.py", line 71, in init_local_doc_qa
    local_doc_qa.init_cfg(mode=args.mode)
  File "/workspace/qanything_local/qanything_kernel/core/local_doc_qa.py", line 51, in init_cfg
    self.llm: ZiyueLLM = ZiyueLLM()
  File "/workspace/qanything_local/qanything_kernel/connector/llm/llm_for_fastchat.py", line 37, in __init__
    self.client = OpenAI(base_url=base_url, api_key="EMPTY")
  File "/usr/local/lib/python3.10/dist-packages/openai/_client.py", line 106, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 745, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 348, in __init__
    self._base_url = self._enforce_trailing_slash(URL(base_url))
  File "/usr/local/lib/python3.10/dist-packages/httpx/_urls.py", line 115, in __init__
    self._uri_reference = urlparse(url, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_urlparse.py", line 246, in urlparse
    parsed_port: typing.Optional[int] = normalize_port(port, scheme)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_urlparse.py", line 348, in normalize_port
    raise InvalidURL(f"Invalid port: {port!r}")
httpx.InvalidURL: Invalid port: 'None'
[2024-03-23 10:47:23 +0800] [143] [ERROR] Not all workers acknowledged a successful startup. Shutting down.

One of your worker processes terminated before startup was completed. Please solve any errors experienced during startup. If you do not see an exception traceback in your error logs, try running Sanic in in a single process using --single-process or single_process=True. Once you are confident that the server is able to start without errors you can switch back to multiprocess mode.
ERROR:sanic.error:Not all workers acknowledged a successful startup. Shutting down.

One of your worker processes terminated before startup was completed. Please solve any errors experienced during startup. If you do not see an exception traceback in your error logs, try running Sanic in in a single process using --single-process or single_process=True. Once you are confident that the server is able to start without errors you can switch back to multiprocess mode.
[2024-03-23 10:47:23 +0800] [143] [INFO] Killing Sanic-Server-0-0 [1124]
INFO:sanic.root:Killing Sanic-Server-0-0 [1124]
[2024-03-23 10:47:23 +0800] [143] [INFO] Killing Sanic-Server-1-0 [1125]
INFO:sanic.root:Killing Sanic-Server-1-0 [1125]
[2024-03-23 10:47:23 +0800] [143] [INFO] Killing Sanic-Server-2-0 [1126]
INFO:sanic.root:Killing Sanic-Server-2-0 [1126]
[2024-03-23 10:47:23 +0800] [143] [INFO] Killing Sanic-Server-3-0 [1127]
INFO:sanic.root:Killing Sanic-Server-3-0 [1127]
[2024-03-23 10:47:23 +0800] [143] [INFO] Killing Sanic-Server-4-0 [1128]
INFO:sanic.root:Killing Sanic-Server-4-0 [1128]
[2024-03-23 10:47:23 +0800] [143] [INFO] Killing Sanic-Server-5-0 [1129]
INFO:sanic.root:Killing Sanic-Server-5-0 [1129]
[2024-03-23 10:47:23 +0800] [143] [INFO] Killing Sanic-Server-6-0 [1130]
INFO:sanic.root:Killing Sanic-Server-6-0 [1130]
[2024-03-23 10:47:23 +0800] [143] [INFO] Killing Sanic-Server-7-0 [1131]
INFO:sanic.root:Killing Sanic-Server-7-0 [1131]
[2024-03-23 10:47:23 +0800] [143] [INFO] Killing Sanic-Server-8-0 [1132]
INFO:sanic.root:Killing Sanic-Server-8-0 [1132]
[2024-03-23 10:47:23 +0800] [143] [INFO] Killing Sanic-Server-9-0 [1133]
INFO:sanic.root:Killing Sanic-Server-9-0 [1133]
[2024-03-23 10:47:23 +0800] [143] [INFO] Server Stopped
INFO:sanic.root:Server Stopped
UPLOAD_ROOT_PATH: /workspace/qanything_local/QANY_DB/content
llm_api_serve_port: None
rerank_port: None
embed_port: None
<Logger debug_logger (INFO)> <Logger qa_logger (INFO)>

```

### 运行环境 | Environment

```Markdown
- OS:WIN10
- NVIDIA Driver:551.61
- CUDA:12.4
- docker:Docker version 25.0.3, build 4debf41
- docker-compose:Docker Compose version v2.24.6-desktop.1
- NVIDIA GPU:NVIDIA RTX A4000
- NVIDIA GPU Memory:16376MiB
```

**Comment by 62bit** [comment]
我删除了.env文件，跑起来了
