### ISSUE TITLE
[BUG]WIN10 WSL下MiniChat-2-3B加载出错

### ISSUE THREAD

**Issue by yy307** [netease-youdao/QAnything#212]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

WIN10系统,运行不了默认的7B模型, 切换到MiniChat-2-3B
v1.2.0和v1.3.0版本启动均报错(前端服务正常运行, 解析服务正常, 回答问题时报错 ):
qanything-container-local  | 前端服务已就绪!...(7/8)
qanything-container-local  | I0405 02:00:49.501050 133 grpc_server.cc:377] Thread started for CommonHandler
qanything-container-local  | I0405 02:00:49.501190 133 infer_handler.cc:629] New request handler for ModelInferHandler, 0
qanything-container-local  | I0405 02:00:49.501236 133 infer_handler.h:1025] Thread started for ModelInferHandler
qanything-container-local  | I0405 02:00:49.501374 133 infer_handler.cc:629] New request handler for ModelInferHandler, 0
qanything-container-local  | I0405 02:00:49.501420 133 infer_handler.h:1025] Thread started for ModelInferHandler
qanything-container-local  | I0405 02:00:49.501526 133 stream_infer_handler.cc:122] New request handler for ModelStreamInferHandler, 0
qanything-container-local  | I0405 02:00:49.501569 133 infer_handler.h:1025] Thread started for ModelStreamInferHandler
qanything-container-local  | I0405 02:00:49.501584 133 grpc_server.cc:2450] Started GRPCInferenceService at 0.0.0.0:9001qanything-container-local  | I0405 02:00:49.502144 133 http_server.cc:3555] Started HTTPService at 0.0.0.0:9000
qanything-container-local  | I0405 02:00:49.544174 133 http_server.cc:185] Started Metrics Service at 0.0.0.0:9002
qanything-container-local  | I0405 02:01:33.781230 133 http_server.cc:3449] HTTP request: 0 /v2/health/ready
qanything-container-local  | The embedding and rerank service is ready!. (7.5/8)
qanything-container-local  | Embedding 和 Rerank 服务已准备就绪！(7.5/8)
**qanything-container-local  | 2024-04-05 10:00:50 | ERROR | stderr |     tokenizer = cls(*init_inputs, **init_kwargs)
qanything-container-local  | 2024-04-05 10:00:50 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/transformers/models/llama/tokenization_llama.py", line 178, in __init__
qanything-container-local  | 2024-04-05 10:00:50 | ERROR | stderr |     self.sp_model = self.get_spm_processor(kwargs.pop("from_slow", False))
qanything-container-local  | 2024-04-05 10:00:50 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/transformers/models/llama/tokenization_llama.py", line 203, in get_spm_processor
qanything-container-local  | 2024-04-05 10:00:50 | ERROR | stderr |     tokenizer.Load(self.vocab_file)
qanything-container-local  | 2024-04-05 10:00:50 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/sentencepiece/__init__.py", line 905, in Load
qanything-container-local  | 2024-04-05 10:00:50 | ERROR | stderr |     return self.LoadFromFile(model_file)
qanything-container-local  | 2024-04-05 10:00:50 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/sentencepiece/__init__.py", line 310, in LoadFromFile
qanything-container-local  | 2024-04-05 10:00:50 | ERROR | stderr |     return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
qanything-container-local  | 2024-04-05 10:00:50 | ERROR | stderr | RuntimeError: Internal: src/sentencepiece_processor.cc(1101) [model_proto->ParseFromArray(serialized.data(), serialized.size())]**

### 期望行为 | Expected Behavior

正常运行

### 运行环境 | Environment

```Markdown
- OS:WIN10 WSL2
- NVIDIA Driver:551.86
- CUDA: 12.4
- docker: WIN10 docker desktop v4.28.0 use the WSL2 based engine
- docker-compose:
- NVIDIA GPU:NVIDIA GeForce RTX 3060
- NVIDIA GPU Memory:12GB
```

### QAnything日志 | QAnything logs

2024-04-05 10:17:40 | INFO | model_worker | args: Namespace(host='0.0.0.0', port=7801, worker_address='http://0.0.0.0:7801', controller_address='http://0.0.0.0:7800', model_path='/model_repos/CustomLLM/MiniChat-2-3B', revision='main', device='cuda', gpus='0', num_gpus=1, max_gpu_memory=None, dtype='bfloat16', load_8bit=True, cpu_offloading=False, gptq_ckpt=None, gptq_wbits=16, gptq_groupsize=-1, gptq_act_order=False, awq_ckpt=None, awq_wbits=16, awq_groupsize=-1, enable_exllama=False, exllama_max_seq_len=4096, exllama_gpu_split=None, exllama_cache_8bit=False, enable_xft=False, xft_max_seq_len=4096, xft_dtype=None, model_names=None, conv_template='minichat', embed_in_truncate=False, limit_worker_concurrency=5, stream_interval=2, no_register=False, seed=None, debug=False, ssl=False)
2024-04-05 10:17:40 | INFO | model_worker | Loading the model ['MiniChat-2-3B'] on worker 0a33f257 ...
You are using the default legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
2024-04-05 10:17:40 | ERROR | stderr | Traceback (most recent call last):
2024-04-05 10:17:40 | ERROR | stderr |   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
2024-04-05 10:17:40 | ERROR | stderr |     return _run_code(code, main_globals, None,
2024-04-05 10:17:40 | ERROR | stderr |   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
2024-04-05 10:17:40 | ERROR | stderr |     exec(code, run_globals)
2024-04-05 10:17:40 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/fastchat/serve/model_worker.py", line 375, in <module>
2024-04-05 10:17:40 | ERROR | stderr |     args, worker = create_model_worker()
2024-04-05 10:17:40 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/fastchat/serve/model_worker.py", line 346, in create_model_worker
2024-04-05 10:17:40 | ERROR | stderr |     worker = ModelWorker(
2024-04-05 10:17:40 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/fastchat/serve/model_worker.py", line 77, in __init__
2024-04-05 10:17:40 | ERROR | stderr |     self.model, self.tokenizer = load_model(
2024-04-05 10:17:40 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/fastchat/model/model_adapter.py", line 277, in load_model
2024-04-05 10:17:40 | ERROR | stderr |     model, tokenizer = adapter.load_compress_model(
2024-04-05 10:17:40 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/fastchat/model/model_adapter.py", line 111, in load_compress_model
2024-04-05 10:17:40 | ERROR | stderr |     return load_compress_model(
2024-04-05 10:17:40 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/fastchat/model/compression.py", line 113, in load_compress_model
2024-04-05 10:17:40 | ERROR | stderr |     tokenizer = AutoTokenizer.from_pretrained(
2024-04-05 10:17:40 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/tokenization_auto.py", line 787, in from_pretrained
2024-04-05 10:17:40 | ERROR | stderr |     return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
2024-04-05 10:17:40 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 2028, in from_pretrained
2024-04-05 10:17:40 | ERROR | stderr |     return cls._from_pretrained(
2024-04-05 10:17:40 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 2060, in _from_pretrained
2024-04-05 10:17:40 | ERROR | stderr |     slow_tokenizer = (cls.slow_tokenizer_class)._from_pretrained(
2024-04-05 10:17:40 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 2260, in _from_pretrained
2024-04-05 10:17:40 | ERROR | stderr |     tokenizer = cls(*init_inputs, **init_kwargs)
2024-04-05 10:17:40 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/transformers/models/llama/tokenization_llama.py", line 178, in __init__
2024-04-05 10:17:40 | ERROR | stderr |     self.sp_model = self.get_spm_processor(kwargs.pop("from_slow", False))
2024-04-05 10:17:40 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/transformers/models/llama/tokenization_llama.py", line 203, in get_spm_processor
2024-04-05 10:17:40 | ERROR | stderr |     tokenizer.Load(self.vocab_file)
2024-04-05 10:17:40 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/sentencepiece/__init__.py", line 905, in Load
2024-04-05 10:17:40 | ERROR | stderr |     return self.LoadFromFile(model_file)
2024-04-05 10:17:40 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/sentencepiece/__init__.py", line 310, in LoadFromFile
2024-04-05 10:17:40 | ERROR | stderr |     return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
2024-04-05 10:17:40 | ERROR | stderr | RuntimeError: Internal: src/sentencepiece_processor.cc(1101) [model_proto->ParseFromArray(serialized.data(), serialized.size())]

debug_logs/fastchat_logs/openai_api_server.log
[openai_api_server.log](https://github.com/netease-youdao/QAnything/files/14879170/openai_api_server.log)

### 复现方法 | Steps To Reproduce

稳定复现,切换v1.2.0和v1.3.0都能重复此错误

### 备注 | Anything else?

模型已下载并存储到custom_models目录下
DESKTOP-65CS179:~/QAnything/logs/debug_logs/fastchat_logs$ cd ../../../assets/custom_models/
lyh@DESKTOP-65CS179:~/QAnything/assets/custom_models$ ls
MiniChat-2-3B
DESKTOP-65CS179:~/QAnything/assets/custom_models$
DESKTOP-65CS179:~/QAnything/assets/custom_models$
DESKTOP-65CS179:~/QAnything/assets/custom_models$ cd MiniChat-2-3B/
DESKTOP-65CS179:~/QAnything/assets/custom_models/MiniChat-2-3B$ ls
README.md  config.json  conversation.py  model.safetensors  pytorch_model.bin  special_tokens_map.json  teaser_b.jpg  tokenizer.model  tokenizer_config.json

**Comment by xiaoma1990-git** [comment]
git: 'lfs' is not a git command. See 'git --help'.  ?
