### ISSUE TITLE
[BUG] <title> 使用docker 方式启动，知识库创建成功后，请求时，报500错误

### ISSUE THREAD

**Issue by oliviawang9** [netease-youdao/QAnything#222]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

问问题的时候，提示 500 错误

### 运行环境 | Environment

```Markdown
- OS: Ubuntu 
- NVIDIA Driver: 525.89.02
- CUDA: 12.0
- docker: 24.0.5
- docker-compose: v2.21.0
- NVIDIA GPU: Nvidia A40
- NVIDIA GPU Memory: 48G
```

### QAnything日志 | QAnything logs

查看 sanic_api.log，报错信息为：
elasticsearch.ApiError: ApiError(503, 'search_phase_execution_exception', None)
ERROR:sanic.error:Exception occurred while handling uri: 'http://192.168.51.142:8777/api/local_doc_qa/local_doc_chat'
Traceback (most recent call last):
  File "handle_request", line 132, in handle_request
    "_asgi_lifespan",
  File "/usr/local/lib/python3.10/dist-packages/sanic/response/types.py", line 547, in stream
    await self.streaming_fn(self)
  File "/workspace/qanything_local/qanything_kernel/qanything_server/handler.py", line 355, in generate_answer
    for resp, next_history in local_doc_qa.get_knowledge_based_answer(
  File "/workspace/qanything_local/qanything_kernel/core/local_doc_qa.py", line 225, in get_knowledge_based_answer
    source_documents = self.get_source_documents(retrieval_queries, milvus_kb)
  File "/workspace/qanything_local/qanything_kernel/core/local_doc_qa.py", line 133, in get_source_documents
    batch_result = milvus_kb.search_emb_async(embs=embs, top_k=top_k, queries=queries)
  File "/workspace/qanything_local/qanything_kernel/connector/database/milvus/milvus_client.py", line 181, in search_emb_async
    return future.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/workspace/qanything_local/qanything_kernel/connector/database/milvus/milvus_client.py", line 170, in __search_emb_sync
    es_records = self.client.search(queries)
  File "/workspace/qanything_local/qanything_kernel/connector/database/milvus/es_client.py", line 182, in search
    response = self.client.search(
  File "/usr/local/lib/python3.10/dist-packages/elasticsearch/_sync/client/utils.py", line 446, in wrapped
    return api(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/elasticsearch/_sync/client/__init__.py", line 3836, in search
    return self.perform_request(  # type: ignore[return-value]
  File "/usr/local/lib/python3.10/dist-packages/elasticsearch/_sync/client/_base.py", line 320, in perform_request
    raise HTTP_EXCEPTIONS.get(meta.status, ApiError)(
elasticsearch.ApiError: ApiError(503, 'search_phase_execution_exception', None)

**Comment by standbym** [comment]
同样遇到，无法正常连接es，请问解决了吗

**Comment by oliviawang9** [comment]
还没有解决

**Comment by simonqian** [comment]
es 8.11.4 版本启动会出现这个错误

**Comment by a524144474** [comment]
我遇到原因是磁盘空间不足30G
进入docker中ElasticSearch的实例，查看集群状态：
`curl -X GET "localhost:9200/_cluster/health?pretty"  `
ElasticSearch集群状态发现为red，查看分片shard状态：
`curl -X GET "localhost:9200/_cat/shards" `
发现所有shard状态均为unassigned，查看shard不分配原因：
`curl -X GET "http://localhost:9200/_cluster/allocation/explain?pretty"   `
发现原因之一：the node is above the high watermark cluster setting [cluster.routing.allocation.disk.watermark.high=95%], using more disk space than the maximum allowed [95.0%], actual free: [4.055101177689788%]
清理磁盘后部分分片状态恢复正常，能正常问答，但仍有一部分分片的状态仍然为unassigned。正常用就先不继续查了-_-

**Comment by fire717** [comment]
> 我遇到原因是磁盘空间不足30G 进入docker中ElasticSearch的实例，查看集群状态： `curl -X GET "localhost:9200/_cluster/health?pretty" ` ElasticSearch集群状态发现为red，查看分片shard状态： `curl -X GET "localhost:9200/_cat/shards" ` 发现所有shard状态均为unassigned，查看shard不分配原因： `curl -X GET "http://localhost:9200/_cluster/allocation/explain?pretty" ` 发现原因之一：the node is above the high watermark cluster setting [cluster.routing.allocation.disk.watermark.high=95%], using more disk space than the maximum allowed [95.0%], actual free: [4.055101177689788%] 清理磁盘后部分分片状态恢复正常，能正常问答，但仍有一部分分片的状态仍然为unassigned。正常用就先不继续查了-_-

确实 我这是37G空间但是也报错，清理到70多G就正常了...
