### ISSUE TITLE
[BUG] python3 纯净模式ubuntu安装失败

### ISSUE THREAD

**Issue by mio4kon** [netease-youdao/QAnything#261]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

python3 -m qanything_kernel.qanything_server.sanic_api --host 0.0.0.0 --port 8777 --model_size 7B       
LOCAL DATA PATH: /home/xxx/QAnything/QANY_DB/content
LOCAL_RERANK_REPO: netease-youdao/bce-reranker-base_v1
LOCAL_EMBED_REPO: netease-youdao/bce-embedding-base_v1
<Logger debug_logger (INFO)> <Logger qa_logger (INFO)>
Traceback (most recent call last):
  File "/home/xxx/miniconda3/envs/qanything-python/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/xxx/miniconda3/envs/qanything-python/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/xxx/QAnything/qanything_kernel/qanything_server/sanic_api.py", line 24, in <module>
    from qanything_kernel.utils.general_utils import download_file, get_gpu_memory_utilization, check_package_version
  File "/home/xxx/QAnything/qanything_kernel/utils/general_utils.py", line 13, in <module>
    import torch
  File "/home/xxx/miniconda3/envs/qanything-python/lib/python3.10/site-packages/torch/__init__.py", line 237, in <module>
    from torch._C import *  # noqa: F403
ImportError: libcudnn.so.8: cannot open shared object file: No such file or directory

### 期望行为 | Expected Behavior

参考 https://github.com/netease-youdao/QAnything/blob/qanything-python-v1.3.1/README.md#pure-python-environment-installation-guide 方式安装，在运行时发生了上述报错。

### 运行环境 | Environment

```Markdown
- OS: 22.04.1-Ubuntu
- NVIDIA Driver: 535.171
- CUDA:Cuda compilation tools, release 11.5, V11.5.119
- docker:25.0.4
- docker-compose:v2.20.3
- NVIDIA GPU:4090
- NVIDIA GPU Memory: 25G
```

### QAnything日志 | QAnything logs

 File "/home/xxx/QAnything/qanything_kernel/utils/general_utils.py", line 13, in <module>
    import torch
  File "/home/xxx/miniconda3/envs/qanything-python/lib/python3.10/site-packages/torch/__init__.py", line 237, in <module>
    from torch._C import *  # noqa: F403
ImportError: libcudnn.so.8: cannot open shared object file: No such file or directory

**Comment by everiori** [comment]
完全相同的问题
<img width="1624" alt="image" src="https://github.com/netease-youdao/QAnything/assets/5765846/76a947d0-7078-4d4c-afd7-e8d5b76de1ae">

**Comment by cloudyangel** [comment]
之前成功启动了几次并且建立数据库，但是刚刚也遇到这个问题。

**Comment by cloudyangel** [comment]
将llm启动超时的判定时间从120改成了1200.
![image](https://github.com/netease-youdao/QAnything/assets/31439796/489c24e5-41cb-4185-8aee-41f12ed6d2b4)

虽然上述报错还在，但是可以正常运行了, 见下图。从加载时间用了238s来看，原来的120s就报错确实太短了，供参考。
![image](https://github.com/netease-youdao/QAnything/assets/31439796/d73f4baf-cd5d-400c-80a4-a6819dd9a118)
![image](https://github.com/netease-youdao/QAnything/assets/31439796/f2c035f7-4c1f-459e-9a7c-297904a4a4f3)
