### ISSUE TITLE
WIN11下 [193] [ERROR] Experienced exception while trying to serve

### ISSUE THREAD

**Issue by zmm1996** [netease-youdao/QAnything#267]
**机器配置**
Windows 11 专业版
16.0 GB
NVIDIA GeForce RTX 3050 Laptop GPU

**运行命令**
`bash ./run.sh -c local -i 0 -b hf -m Qwen-7B-QAnything -t qwen-7b-qanything`
选择1.8B

![image](https://github.com/netease-youdao/QAnything/assets/40532959/24946c1c-6e13-4509-a411-023261d1563b)
![image](https://github.com/netease-youdao/QAnything/assets/40532959/40c29ec2-10ea-4d05-9962-8bff889ef4ae)

**sanic_api.log日志内容**

UPLOAD_ROOT_PATH: /workspace/qanything_local/QANY_DB/content
llm_api_serve_port: 7802
rerank_port: 9001
embed_port: 9001
<Logger debug_logger (INFO)> <Logger qa_logger (INFO)>
INFO:root:OPENAI_API_BASE = None
INFO:root:OPENAI_API_MODEL_NAME = None
[2024-04-17 18:36:36 +0800] [193] [INFO] Sanic v23.6.0
INFO:sanic.root:Sanic v23.6.0
[2024-04-17 18:36:36 +0800] [193] [INFO] Goin' Fast @ http://0.0.0.0:8777
INFO:sanic.root:Goin' Fast @ http://0.0.0.0:8777
[2024-04-17 18:36:36 +0800] [193] [INFO] mode: production, w/ 10 workers
INFO:sanic.root:mode: production, w/ 10 workers
[2024-04-17 18:36:36 +0800] [193] [INFO] server: sanic, HTTP/1.1
INFO:sanic.root:server: sanic, HTTP/1.1
[2024-04-17 18:36:36 +0800] [193] [INFO] python: 3.10.12
INFO:sanic.root:python: 3.10.12
[2024-04-17 18:36:36 +0800] [193] [INFO] platform: Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
INFO:sanic.root:platform: Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
[2024-04-17 18:36:36 +0800] [193] [INFO] packages: sanic-routing==23.12.0, sanic-ext==23.6.0
INFO:sanic.root:packages: sanic-routing==23.12.0, sanic-ext==23.6.0
INFO:root:OPENAI_API_BASE = None
INFO:root:OPENAI_API_MODEL_NAME = None
[2024-04-17 18:37:41 +0800] [193] [ERROR] Experienced exception while trying to serve
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sanic/mixins/startup.py", line 880, in serve
    manager.run()
  File "/usr/local/lib/python3.10/dist-packages/sanic/worker/manager.py", line 122, in run
    self.monitor()
  File "/usr/local/lib/python3.10/dist-packages/sanic/worker/manager.py", line 183, in monitor
    self.wait_for_ack()
  File "/usr/local/lib/python3.10/dist-packages/sanic/worker/manager.py", line 239, in wait_for_ack
    while not self._all_workers_ack():
  File "/usr/local/lib/python3.10/dist-packages/sanic/worker/manager.py", line 308, in _all_workers_ack
    for worker_state in self.worker_state.values()
  File "<string>", line 2, in values
  File "/usr/lib/python3.10/multiprocessing/managers.py", line 817, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
ERROR:sanic.error:Experienced exception while trying to serve
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sanic/mixins/startup.py", line 880, in serve
    manager.run()
  File "/usr/local/lib/python3.10/dist-packages/sanic/worker/manager.py", line 122, in run
    self.monitor()
  File "/usr/local/lib/python3.10/dist-packages/sanic/worker/manager.py", line 183, in monitor
    self.wait_for_ack()
  File "/usr/local/lib/python3.10/dist-packages/sanic/worker/manager.py", line 239, in wait_for_ack
    while not self._all_workers_ack():
  File "/usr/local/lib/python3.10/dist-packages/sanic/worker/manager.py", line 308, in _all_workers_ack
    for worker_state in self.worker_state.values()
  File "<string>", line 2, in values
  File "/usr/lib/python3.10/multiprocessing/managers.py", line 817, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
[2024-04-17 18:37:41 +0800] [193] [INFO] Server Stopped
INFO:sanic.root:Server Stopped
Traceback (most recent call last):
  File "/workspace/qanything_local/qanything_kernel/qanything_server/sanic_api.py", line 89, in <module>
    app.run(host='0.0.0.0', port=8777, workers=10, access_log=False)
  File "/usr/local/lib/python3.10/dist-packages/sanic/mixins/startup.py", line 215, in run
    serve(primary=self)  # type: ignore
  File "/usr/local/lib/python3.10/dist-packages/sanic/mixins/startup.py", line 880, in serve
    manager.run()
  File "/usr/local/lib/python3.10/dist-packages/sanic/worker/manager.py", line 122, in run
    self.monitor()
  File "/usr/local/lib/python3.10/dist-packages/sanic/worker/manager.py", line 183, in monitor
    self.wait_for_ack()
  File "/usr/local/lib/python3.10/dist-packages/sanic/worker/manager.py", line 239, in wait_for_ack
    while not self._all_workers_ack():
  File "/usr/local/lib/python3.10/dist-packages/sanic/worker/manager.py", line 308, in _all_workers_ack
    for worker_state in self.worker_state.values()
  File "<string>", line 2, in values
  File "/usr/lib/python3.10/multiprocessing/managers.py", line 817, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

**Comment by zmm1996** [comment]
使用openai.依然报错

`bash ./run.sh -c cloud -i 0 -b default`

![image](https://github.com/netease-youdao/QAnything/assets/40532959/e0e9a172-f6c3-43dc-9c03-c039d9afe9ca)
![image](https://github.com/netease-youdao/QAnything/assets/40532959/1ff75898-316e-445b-a04e-4d459ad36af2)
