### ISSUE TITLE
[BUG] 2个并发就报错

### ISSUE THREAD

**Issue by xuzhenjun130** [netease-youdao/QAnything#296]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

ab 并发请求
```
ab -p post.txt -T 'application/json' -c 2 -n 1000 http://192.168.100.143:8777/api/local_doc_qa/local_doc_chat
```

post.txt 

```json
{
    "kb_ids": [
        "KBaf81b7f612ea41a6ad7a6841a1de0080",
        "KBe94f1ea3c4c64417ba7d7325c5772f5c"
    ],
    "question": "你是谁",
    "user_id": "zzp",
    "streaming": true,
    "history": [
    ]
}
```

此时单独post 请求

```bash
 curl --location --request POST 'http://192.168.100.143:8777/api/local_doc_qa/local_doc_chat' \
--header 'User-Agent: Apifox/1.0.0 (https://apifox.com)' \
--header 'Content-Type: application/json' \
--data-raw '{
    "kb_ids": [
        "KBaf81b7f612ea41a6ad7a6841a1de0080",
        "KBe94f1ea3c4c64417ba7d7325c5772f5c"
    ],
    "question": "你是谁？",
    "user_id": "zzp",
    "streaming": true,
    "history": [
    ]
}'

```

此时接口响应：
data: {"code": 200, "msg": "success", "question": "", "response": "'NoneType' object is not subscriptable", "history": [], "source_documents": []}

### 期望行为 | Expected Behavior

并发差，恢复慢都可以接受，这直接报错就难以理解了

希望能正常返回数据：
data: {"code": 200, "msg": "success", "question": "", "response": "我是", "history": [], "source_documents": []}

### 运行环境 | Environment

```Markdown
- OS: centos 7
- NVIDIA Driver: 535.161.07
- CUDA: 12.2
- docker:25.0.4
- docker-compose: v2.24.7
- NVIDIA GPU: rtx 4090
- NVIDIA GPU Memory: 24G
```

### QAnything日志 | QAnything logs

```
INFO:root:prompt tokens: 1123
INFO:root:streaming: True
INFO:root:[{'role': 'user', 'content': '参考信息：\n你是xxxx，简洁但不丢信息，不要胡乱编造。\n你的回复：'}]
INFO:httpx:HTTP Request: POST http://localhost:7802/v1/chat/completions "HTTP/1.1 200 OK"
Exception ignored in: <generator object OpenAICustomLLM._call at 0x78a664a2b4c0>
Traceback (most recent call last):
  File "/workspace/qanything_local/qanything_kernel/core/local_doc_qa.py", line 255, in get_knowledge_based_answer
    yield response, history
RuntimeError: generator ignored GeneratorExit
INFO:root:Error calling API: 'NoneType' object is not subscriptable
Exception ignored in: <generator object OpenAICustomLLM._call at 0x72f3fc21e180>
Traceback (most recent call last):
  File "/workspace/qanything_local/qanything_kernel/core/local_doc_qa.py", line 255, in get_knowledge_based_answer
    yield response, history
RuntimeError: generator ignored GeneratorExit
INFO:root:Error calling API: 'NoneType' object is not subscriptable
Exception ignored in: <generator object OpenAICustomLLM._call at 0x7f9c5cc22f80>
Traceback (most recent call last):
  File "/workspace/qanything_local/qanything_kernel/core/local_doc_qa.py", line 255, in get_knowledge_based_answer
    yield response, history
RuntimeError: generator ignored GeneratorExit
INFO:root:Error calling API: 'NoneType' object is not subscriptable
Exception ignored in: <generator object OpenAICustomLLM._call at 0x74994e1b1c40>
Traceback (most recent call last):
  File "/workspace/qanything_local/qanything_kernel/core/local_doc_qa.py", line 255, in get_knowledge_based_answer
    yield response, history
RuntimeError: generator ignored GeneratorExit
Exception ignored in: <generator object OpenAICustomLLM._call at 0x74994e1b1930>
Traceback (most recent call last):
  File "/workspace/qanything_local/qanything_kernel/core/local_doc_qa.py", line 255, in get_knowledge_based_answer
    yield response, history
RuntimeError: generator ignored GeneratorExit
```

### 备注 | Anything else?

没有并发的时候，测试是ok的，没有报错

**Comment by truthsun22** [comment]
同问，是fastchat底层机制吗？

**Comment by CamDX3906** [comment]
问题解决了吗？我这里并发没有报错，但是并发量太差了 ，tps =1 ，用的是 1080it 显卡，对接的是openAI 模型，在考虑是不是要升级一下显卡，不知道能不能解决这个并发的问题

**Comment by xuzhenjun130** [comment]
默认启动用的是fastchat，并发太差了。
后面用vllm 部署，并发提高了很多，并发能支持20-30，勉强能能用了

@CamDX3906 
@truthsun22 

> 用python安装版，简单好改代码
