### ISSUE TITLE
[BUG] ValueError: No available memory for the cache blocks. Try increasing `gpu_memory_utilization` when initializing the engine.

### ISSUE THREAD

**Issue by huweibin1983** [netease-youdao/QAnything#302]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

ValueError: No available memory for the cache blocks. Try increasing `gpu_memory_utilization` when initializing the engine.

### 期望行为 | Expected Behavior

请教修改方法，显卡是RTX3090，WIN11，DOCKER部署

### 运行环境 | Environment

```Markdown
- OS:Win11
- NVIDIA Driver:RTX3090
- CUDA:
- docker:
- docker-compose:
- NVIDIA GPU:
- NVIDIA GPU Memory:24G
```

### QAnything日志 | QAnything logs

INFO 04-27 10:11:03 llm_engine.py:70] Initializing an LLM engine with config: model='/model_repos/CustomLLM/Qwen-7B-QAnything', tokenizer='/model_repos/CustomLLM/Qwen-7B-QAnything', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.bfloat16, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=1, quantization=None, enforce_eager=False, seed=0)
INFO 04-27 10:13:05 llm_engine.py:275] # GPU blocks: 0, # CPU blocks: 256
2024-04-27 10:13:05 | ERROR | stderr | Traceback (most recent call last):
2024-04-27 10:13:05 | ERROR | stderr |   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
2024-04-27 10:13:05 | ERROR | stderr |     return _run_code(code, main_globals, None,
2024-04-27 10:13:05 | ERROR | stderr |   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
2024-04-27 10:13:05 | ERROR | stderr |     exec(code, run_globals)
2024-04-27 10:13:05 | ERROR | stderr |   File "/workspace/qanything_local/third_party/FastChat/fastchat/serve/vllm_worker.py", line 271, in <module>
2024-04-27 10:13:05 | ERROR | stderr |     engine = AsyncLLMEngine.from_engine_args(engine_args)
2024-04-27 10:13:05 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 500, in from_engine_args
2024-04-27 10:13:05 | ERROR | stderr |     engine = cls(parallel_config.worker_use_ray,
2024-04-27 10:13:05 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 273, in __init__
2024-04-27 10:13:05 | ERROR | stderr |     self.engine = self._init_engine(*args, **kwargs)
2024-04-27 10:13:05 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 318, in _init_engine
2024-04-27 10:13:05 | ERROR | stderr |     return engine_class(*args, **kwargs)
2024-04-27 10:13:05 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 114, in __init__
2024-04-27 10:13:05 | ERROR | stderr |     self._init_cache()
2024-04-27 10:13:05 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 279, in _init_cache
2024-04-27 10:13:05 | ERROR | stderr |     raise ValueError("No available memory for the cache blocks. "
2024-04-27 10:13:05 | ERROR | stderr | ValueError: No available memory for the cache blocks. Try increasing `gpu_memory_utilization` when initializing the engine.

**Comment by huweibin1983** [comment]
bash ./run.sh -c local -i 0 -b vllm -m Qwen-7B-QAnything -t qwen-7b-qanything -p 1 -r 0.85
将启动指令改为
bash ./run.sh -c local -i 0 -b vllm -m Qwen-7B-QAnything -t qwen-7b-qanything -p 1 -r 0.95后可以正常启动。
