### ISSUE TITLE
ModuleNotFoundError: No module named 'faster_whisper'

### ISSUE THREAD

**Issue by Jaren0702** [netease-youdao/QAnything#312]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

ModuleNotFoundError: No module named 'faster_whisper'

(QAnything) jarenzhao@JarendeMacBook-Air QAnything-1.4.0-python % bash scripts/run_for_3B_in_M1_mac.sh                                 
Xcode 已正确安装在路径：/Applications/Xcode.app/Contents/Developer
即将启动后端服务，启动成功后请复制[http://0.0.0.0:8777/qanything/]到浏览器进行测试。
运行qanything-server的命令是：
CUDA_VISIBLE_DEVICES=0 python3 -m qanything_kernel.qanything_server.sanic_api --host 0.0.0.0 --port 8777 --model_size 3B       
LOCAL DATA PATH: /Users/jarenzhao/sources/github/QAnything-1.4.0-python/QANY_DB/content
LOCAL_RERANK_REPO: maidalun/bce-reranker-base_v1
LOCAL_EMBED_REPO: maidalun/bce-embedding-base_v1
<Logger debug_logger (INFO)> <Logger qa_logger (INFO)>
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/jarenzhao/sources/github/QAnything-1.4.0-python/qanything_kernel/qanything_server/sanic_api.py", line 34, in <module>
    from .handler import *
  File "/Users/jarenzhao/sources/github/QAnything-1.4.0-python/qanything_kernel/qanything_server/handler.py", line 1, in <module>
    from qanything_kernel.core.local_file import LocalFile
  File "/Users/jarenzhao/sources/github/QAnything-1.4.0-python/qanything_kernel/core/local_file.py", line 5, in <module>
    from qanything_kernel.utils.loader.my_recursive_url_loader import MyRecursiveUrlLoader
  File "/Users/jarenzhao/sources/github/QAnything-1.4.0-python/qanything_kernel/utils/loader/__init__.py", line 3, in <module>
    from .audio_loader import UnstructuredPaddleAudioLoader
  File "/Users/jarenzhao/sources/github/QAnything-1.4.0-python/qanything_kernel/utils/loader/audio_loader.py", line 8, in <module>
    from faster_whisper import WhisperModel
ModuleNotFoundError: No module named 'faster_whisper'

### 运行环境 | Environment

```Markdown
- OS: macOS 14.4.1
- M1
```

### 复现方法 | Steps To Reproduce

1. pip install -r requirements.txt
2. bash scripts/run_for_3B_in_M1_mac.sh

**Comment by kerneltravel** [comment]
same occured when run on Linux by ```bash scripts/run_for_7B_in_Linux_or_WSL.sh``` . 
solved by ```pip install  faster_whisper```
