### ISSUE TITLE
使用v1.3.3版本启动qwen-7b-chat模型失败

### ISSUE THREAD

**Issue by cmf722123** [netease-youdao/QAnything#315]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

使用v1.3.3版本启动qwen-7b-chat模型失败

### 运行环境 | Environment

```Markdown
- OS:ubuntu16.04
- NVIDIA Driver:550.54.14
- CUDA:12.4
- docker:20.10.7
- docker-compose:2.24.0
- NVIDIA GPU:GeForce RTX 4070ti
- NVIDIA GPU Memory:16GB
```

### QAnything日志 | QAnything logs

fschat_model_worker_7801.log：
2024-05-07 17:29:40 | INFO | model_worker | args: Namespace(host='0.0.0.0', port=7801, worker_address='http://0.0.0.0:7801', controller_address='http://0.0.0.0:7800', model_path='/model_repos/CustomLLM/Qwen-7B-Chat', revision='main', device='cuda', gpus='0', num_gpus=1, max_gpu_memory=None, dtype='bfloat16', load_8bit=True, cpu_offloading=False, gptq_ckpt=None, gptq_wbits=16, gptq_groupsize=-1, gptq_act_order=False, awq_ckpt=None, awq_wbits=16, awq_groupsize=-1, enable_exllama=False, exllama_max_seq_len=4096, exllama_gpu_split=None, exllama_cache_8bit=False, enable_xft=False, xft_max_seq_len=4096, xft_dtype=None, model_names=None, conv_template='qwen-7b-chat', embed_in_truncate=False, limit_worker_concurrency=5, stream_interval=2, no_register=False, seed=None, debug=False, ssl=False)
2024-05-07 17:29:40 | INFO | model_worker | Loading the model ['Qwen-7B-Chat'] on worker b4aa384c ...
2024-05-07 17:29:40 | ERROR | stderr | Traceback (most recent call last):
2024-05-07 17:29:40 | ERROR | stderr |   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
2024-05-07 17:29:40 | ERROR | stderr |     return _run_code(code, main_globals, None,
2024-05-07 17:29:40 | ERROR | stderr |   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
2024-05-07 17:29:40 | ERROR | stderr |     exec(code, run_globals)
2024-05-07 17:29:40 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/fastchat/serve/model_worker.py", line 375, in <module>
2024-05-07 17:29:40 | ERROR | stderr |     args, worker = create_model_worker()
2024-05-07 17:29:40 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/fastchat/serve/model_worker.py", line 346, in create_model_worker
2024-05-07 17:29:40 | ERROR | stderr |     worker = ModelWorker(
2024-05-07 17:29:40 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/fastchat/serve/model_worker.py", line 77, in __init__
2024-05-07 17:29:40 | ERROR | stderr |     self.model, self.tokenizer = load_model(
2024-05-07 17:29:40 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/fastchat/model/model_adapter.py", line 277, in load_model
2024-05-07 17:29:40 | ERROR | stderr |     model, tokenizer = adapter.load_compress_model(
2024-05-07 17:29:40 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/fastchat/model/model_adapter.py", line 111, in load_compress_model
2024-05-07 17:29:40 | ERROR | stderr |     return load_compress_model(
2024-05-07 17:29:40 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/fastchat/model/compression.py", line 113, in load_compress_model
2024-05-07 17:29:40 | ERROR | stderr |     tokenizer = AutoTokenizer.from_pretrained(
2024-05-07 17:29:40 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/tokenization_auto.py", line 784, in from_pretrained
2024-05-07 17:29:40 | ERROR | stderr |     raise ValueError(
2024-05-07 17:29:40 | ERROR | stderr | ValueError: Tokenizer class QWenTokenizer does not exist or is not currently imported.

### 复现方法 | Steps To Reproduce

执行bash ./run.sh -c local -i 0 -b hf -m Qwen-7B-Chat -t qwen-7b-chat后无法启动

**Comment by Lu0Key** [comment]
我也遇到了同样的错误，都是es连不上

**Comment by cmf722123** [comment]
> 我也遇到了同样的错误，都是es连不上

老哥你解决了吗 我现在是用的1.2.0的分支

**Comment by Lu0Key** [comment]
> > 我也遇到了同样的错误，都是es连不上
> 
> 老哥你解决了吗 我现在是用的1.2.0的分支

我没解决，用1.2.0就能跑起来吗

**Comment by Lu0Key** [comment]
我用1.2.0也没跑起来
