### ISSUE TITLE
[BUG] <Run With Openai API On Windows WSL or Linux，CPU Only> 

### ISSUE THREAD

**Issue by eric7733** [netease-youdao/QAnything#330]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

执行bash scripts/run_for_openai_api_with_cpu_in_Linux_or_WSL.sh，报错：
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/eric/QAnything/qanything_kernel/qanything_server/sanic_api.py", line 20, in <module>
    from qanything_kernel.configs.model_config import DT_7B_MODEL_PATH, \
  File "/home/eric/QAnything/qanything_kernel/configs/model_config.py", line 2, in <module>
    import nltk
ModuleNotFoundError: No module named 'nltk'

### 运行环境 | Environment

```Markdown
- OS:Windows 11 WSL2
```

**Comment by GitHubHaoP** [comment]
pip install -e .
需要安装所有依赖包的，要不就会报找不到某个module的错误。

**Comment by Selenium39** [comment]
如果用的是conda，应该把base_run.sh里面的启动由python3改成python,不然还是用的是原来的python环境
![Screenshot 2024-05-28 at 15 44 06](https://github.com/netease-youdao/QAnything/assets/29670394/b49fa918-1123-4e45-9ff6-ded89f203a4c)
