### ISSUE TITLE
安装了 nltk 但是不能调用

### ISSUE THREAD

**Issue by yc4805551** [netease-youdao/QAnything#395]
请问
CUDA_VISIBLE_DEVICES=0 python3 -m qanything_kernel.qanything_server.sanic_api --host 0.0.0.0 --port 8777 --model_size 3B
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/mnt/c/Users/GLY-PC/QAnything/qanything_kernel/qanything_server/sanic_api.py", line 20, in <module>
    from qanything_kernel.configs.model_config import DT_7B_MODEL_PATH, \
  File "/mnt/c/Users/GLY-PC/QAnything/qanything_kernel/configs/model_config.py", line 2, in <module>
    import nltk
ModuleNotFoundError: No module named 'nltk'

**Comment by num-doc** [comment]
请问解决了吗  我也是这个问题   nltk  安装包没问题 但是就是报错

**Comment by sanwei111** [comment]
请问还需要下载nltk_data吗

**Comment by num-doc** [comment]
> 请问还需要下载nltk_data吗

不用下载 不是nltk_data 的问题  是model_config.py的问题  你把nltk 相关的注释掉就行  但是建议不要用qanythinng   稳定性很差  效果也不好

**Comment by sanwei111** [comment]
> > 请问还需要下载nltk_data吗
> 
> 不用下载 不是nltk_data 的问题 是model_config.py的问题 你把nltk 相关的注释掉就行 但是建议不要用qanythinng 稳定性很差 效果也不好

哈哈，其实还是文件解析分块这里
