### ISSUE TITLE
[BUG] <title>如何完全重置 

### ISSUE THREAD

**Issue by fire717** [netease-youdao/QAnything#415]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

之前用过1.2.0没什么问题，最近更新尝试拉了master的代码，重新拉了docker，跑起来发现第二个知识库老是解析失败，于是尝试删除所有数据完全重置：
1. 删除代码，重新拉取了新的master代码
2. docker compose down -v删除所有数据和容器
3. 重新执行sh run.sh
使用云端api大模型，然后启动不起来，看日志说
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/mysql/connector/connection_cext.py", line 308, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
_mysql_connector.MySQLInterfaceError: Can't connect to MySQL server on 'mysql-container-local:3306' (111)
```
在issue搜到一个，说吧volume删掉，然后去掉docker配置中mysql的端口注释，的确可以启动了，但是启动进去上传数据解析失败，聊天也不行，删除文件也不行。
尝试删除所有数据重新启动，依旧又起不起来报错MySQL连不上

### 期望行为 | Expected Behavior

正常启动

### 运行环境 | Environment

```Markdown
- OS:Ubuntu18
- NVIDIA Driver:
- CUDA:
- docker: 24.0.2
- docker-compose:
- NVIDIA GPU:3090TI
- NVIDIA GPU Memory:24G
```

### QAnything日志 | QAnything logs

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sanic/worker/serve.py", line 117, in worker_serve
    return _serve_http_1(
  File "/usr/local/lib/python3.10/dist-packages/sanic/server/runners.py", line 223, in _serve_http_1
    loop.run_until_complete(app._server_event("init", "before"))
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.10/dist-packages/sanic/app.py", line 1764, in _server_event
    await self.dispatch(
  File "/usr/local/lib/python3.10/dist-packages/sanic/signals.py", line 208, in dispatch
    return await dispatch
  File "/usr/local/lib/python3.10/dist-packages/sanic/signals.py", line 183, in _dispatch
    raise e
  File "/usr/local/lib/python3.10/dist-packages/sanic/signals.py", line 167, in _dispatch
    retval = await maybe_coroutine
  File "/usr/local/lib/python3.10/dist-packages/sanic/app.py", line 1315, in _listener
    await maybe_coro
  File "/workspace/qanything_local/qanything_kernel/qanything_server/sanic_api.py", line 70, in init_local_doc_qa
    local_doc_qa.init_cfg(mode=args.mode)
  File "/workspace/qanything_local/qanything_kernel/core/local_doc_qa.py", line 54, in init_cfg
    self.milvus_summary = KnowledgeBaseManager(self.mode)
  File "/workspace/qanything_local/qanything_kernel/connector/database/mysql/mysql_client.py", line 18, in __init__
    self.check_database_(host, port, user, password, database)
  File "/workspace/qanything_local/qanything_kernel/connector/database/mysql/mysql_client.py", line 32, in check_database_
    cnx = mysql.connector.connect(
  File "/usr/local/lib/python3.10/dist-packages/mysql/connector/pooling.py", line 293, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/mysql/connector/connection_cext.py", line 129, in __init__
    self.connect(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/mysql/connector/abstracts.py", line 1237, in connect
    self._open_connection()
  File "/usr/local/lib/python3.10/dist-packages/mysql/connector/connection_cext.py", line 313, in _open_connection
    raise get_mysql_exception(
mysql.connector.errors.DatabaseError: 2003 (HY000): Can't connect to MySQL server on 'mysql-container-local:3306' (111)
[2024-06-25 19:18:26 +0800] [133] [ERROR] Not all workers acknowledged a successful startup. Shutting down.

One of your worker processes terminated before startup was completed. Please solve any errors experienced during startup. If you do not see an exception traceback in your error logs, try running Sanic in in a single process using --single-process or single_process=True. Once you are confident that the server is able to start without errors you can switch back to multiprocess mode.
ERROR:sanic.error:Not all workers acknowledged a successful startup. Shutting down.

One of your worker processes terminated before startup was completed. Please solve any errors experienced during startup. If you do not see an exception traceback in your error logs, try running Sanic in in a single process using --single-process or single_process=True. Once you are confident that the server is able to start without errors you can switch back to multiprocess mode.

**Comment by fire717** [comment]
经过排查，不是重置的问题
