### ISSUE TITLE
【急】求助大佬，为什么打开前端没有对话界面（点击新建知识库也提示请求失败

### ISSUE THREAD

**Issue by yyinchan** [netease-youdao/QAnything#416]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

我启动的命令是bash ./run.sh -c local -i. 0 -b hf -m Qwen-7B-QAnything -t qwen-7b-qanything。
之前用同样的命令是可以正常使用的，现在前端显示是这样😭
![图片1](https://github.com/netease-youdao/QAnything/assets/103884644/e22d4ddb-2e48-40c9-910b-d88d4f583768)

### 运行环境 | Environment

```Markdown
OS: Ubuntu 18.04.6
NVIDIA Driver: 550.54.14
CUDA: 12.4
docker: 24.0.2
docker-compose: 2.24.3
NVIDIA GPU: GeForce RTX 3090 Ti
NVIDIA GPU Memory: 24GB*2
```

### QAnything日志 | QAnything logs

UPLOAD_ROOT_PATH: /workspace/qanything_local/QANY_DB/content
llm_api_serve_port: 7802
rerank_port: 9001
embed_port: 9001
<Logger debug_logger (INFO)> <Logger qa_logger (INFO)>
INFO:root:OPENAI_API_BASE = None
INFO:root:OPENAI_API_MODEL_NAME = None
[2024-06-26 21:19:39 +0800] [151] [INFO] Sanic v23.6.0
INFO:sanic.root:Sanic v23.6.0
[2024-06-26 21:19:39 +0800] [151] [INFO] Goin' Fast @ http://0.0.0.0:8777
INFO:sanic.root:Goin' Fast @ http://0.0.0.0:8777
[2024-06-26 21:19:39 +0800] [151] [INFO] mode: production, w/ 10 workers
INFO:sanic.root:mode: production, w/ 10 workers
[2024-06-26 21:19:39 +0800] [151] [INFO] server: sanic, HTTP/1.1
INFO:sanic.root:server: sanic, HTTP/1.1
[2024-06-26 21:19:39 +0800] [151] [INFO] python: 3.10.12
INFO:sanic.root:python: 3.10.12
[2024-06-26 21:19:39 +0800] [151] [INFO] platform: Linux-5.4.0-150-generic-x86_64-with-glibc2.35
INFO:sanic.root:platform: Linux-5.4.0-150-generic-x86_64-with-glibc2.35
[2024-06-26 21:19:39 +0800] [151] [INFO] packages: sanic-routing==23.12.0, sanic-ext==23.6.0
INFO:sanic.root:packages: sanic-routing==23.12.0, sanic-ext==23.6.0
INFO:root:OPENAI_API_BASE = None
INFO:root:OPENAI_API_MODEL_NAME = None
INFO:root:OPENAI_API_BASE = None
INFO:root:OPENAI_API_MODEL_NAME = None
INFO:root:OPENAI_API_BASE = None
INFO:root:OPENAI_API_MODEL_NAME = None
INFO:root:OPENAI_API_BASE = None
INFO:root:OPENAI_API_MODEL_NAME = None
INFO:root:OPENAI_API_BASE = None
INFO:root:OPENAI_API_MODEL_NAME = None
INFO:root:OPENAI_API_BASE = None
INFO:root:OPENAI_API_MODEL_NAME = None
INFO:root:OPENAI_API_BASE = None
INFO:root:OPENAI_API_MODEL_NAME = None
INFO:root:OPENAI_API_BASE = None
INFO:root:OPENAI_API_MODEL_NAME = None
INFO:root:OPENAI_API_BASE = None
INFO:root:OPENAI_API_MODEL_NAME = None
INFO:root:OPENAI_API_BASE = None
INFO:root:OPENAI_API_MODEL_NAME = None
INFO:root:OPENAI_API_BASE = None
INFO:root:OPENAI_API_MODEL_NAME = None
UPLOAD_ROOT_PATH: /workspace/qanything_local/QANY_DB/content
llm_api_serve_port: 7802
rerank_port: 9001
embed_port: 9001
<Logger debug_logger (INFO)> <Logger qa_logger (INFO)>
[2024-06-26 21:19:59 +0800] [814] [INFO] Sanic Extensions:
INFO:sanic.root:Sanic Extensions:
[2024-06-26 21:19:59 +0800] [814] [INFO]   > injection [0 dependencies; 0 constants]
INFO:sanic.root:  > injection [0 dependencies; 0 constants]
[2024-06-26 21:19:59 +0800] [814] [INFO]   > openapi [http://0.0.0.0:8777/docs]
INFO:sanic.root:  > openapi [http://0.0.0.0:8777/docs]
[2024-06-26 21:19:59 +0800] [814] [INFO]   > http
INFO:sanic.root:  > http
[2024-06-26 21:19:59 +0800] [814] [INFO]   > templating [jinja2==3.1.3]
INFO:sanic.root:  > templating [jinja2==3.1.3]
UPLOAD_ROOT_PATH: /workspace/qanything_local/QANY_DB/content
llm_api_serve_port: 7802
rerank_port: 9001
embed_port: 9001
<Logger debug_logger (INFO)> <Logger qa_logger (INFO)>
[2024-06-26 21:19:59 +0800] [806] [INFO] Sanic Extensions:
INFO:sanic.root:Sanic Extensions:
[2024-06-26 21:19:59 +0800] [806] [INFO]   > injection [0 dependencies; 0 constants]
INFO:sanic.root:  > injection [0 dependencies; 0 constants]
[2024-06-26 21:19:59 +0800] [806] [INFO]   > openapi [http://0.0.0.0:8777/docs]
INFO:sanic.root:  > openapi [http://0.0.0.0:8777/docs]
[2024-06-26 21:19:59 +0800] [806] [INFO]   > http
INFO:sanic.root:  > http
[2024-06-26 21:19:59 +0800] [806] [INFO]   > templating [jinja2==3.1.3]
INFO:sanic.root:  > templating [jinja2==3.1.3]
UPLOAD_ROOT_PATH: /workspace/qanything_local/QANY_DB/content
llm_api_serve_port: 7802
rerank_port: 9001
embed_port: 9001
<Logger debug_logger (INFO)> <Logger qa_logger (INFO)>
[2024-06-26 21:19:59 +0800] [807] [INFO] Sanic Extensions:
INFO:sanic.root:Sanic Extensions:
[2024-06-26 21:19:59 +0800] [807] [INFO]   > injection [0 dependencies; 0 constants]
INFO:sanic.root:  > injection [0 dependencies; 0 constants]
[2024-06-26 21:19:59 +0800] [807] [INFO]   > openapi [http://0.0.0.0:8777/docs]
INFO:sanic.root:  > openapi [http://0.0.0.0:8777/docs]
[2024-06-26 21:19:59 +0800] [807] [INFO]   > http
INFO:sanic.root:  > http
[2024-06-26 21:19:59 +0800] [807] [INFO]   > templating [jinja2==3.1.3]
INFO:sanic.root:  > templating [jinja2==3.1.3]
UPLOAD_ROOT_PATH: /workspace/qanything_local/QANY_DB/content
llm_api_serve_port: 7802
rerank_port: 9001
 embed_port: 9001
<Logger debug_logger (INFO)> <Logger qa_logger (INFO)>
[2024-06-26 21:19:59 +0800] [808] [INFO] Sanic Extensions:
INFO:sanic.root:Sanic Extensions:
[2024-06-26 21:19:59 +0800] [808] [INFO]   > injection [0 dependencies; 0 constants]
INFO:sanic.root:  > injection [0 dependencies; 0 constants]
[2024-06-26 21:19:59 +0800] [808] [INFO]   > openapi [http://0.0.0.0:8777/docs]
INFO:sanic.root:  > openapi [http://0.0.0.0:8777/docs]
[2024-06-26 21:19:59 +0800] [808] [INFO]   > http
INFO:sanic.root:  > http
[2024-06-26 21:19:59 +0800] [808] [INFO]   > templating [jinja2==3.1.3]
INFO:sanic.root:  > templating [jinja2==3.1.3]
UPLOAD_ROOT_PATH: /workspace/qanything_local/QANY_DB/content
llm_api_serve_port: 7802
rerank_port: 9001
embed_port: 9001
<Logger debug_logger (INFO)> <Logger qa_logger (INFO)>
[2024-06-26 21:19:59 +0800] [809] [INFO] Sanic Extensions:
INFO:sanic.root:Sanic Extensions:
[2024-06-26 21:19:59 +0800] [809] [INFO]   > injection [0 dependencies; 0 constants]
INFO:sanic.root:  > injection [0 dependencies; 0 constants]
[2024-06-26 21:19:59 +0800] [809] [INFO]   > openapi [http://0.0.0.0:8777/docs]
INFO:sanic.root:  > openapi [http://0.0.0.0:8777/docs]
[2024-06-26 21:19:59 +0800] [809] [INFO]   > http
INFO:sanic.root:  > http
[2024-06-26 21:19:59 +0800] [809] [INFO]   > templating [jinja2==3.1.3]
INFO:sanic.root:  > templating [jinja2==3.1.3]
UPLOAD_ROOT_PATH: /workspace/qanything_local/QANY_DB/content
llm_api_serve_port: 7802
rerank_port: 9001
embed_port: 9001
<Logger debug_logger (INFO)> <Logger qa_logger (INFO)>
[2024-06-26 21:19:59 +0800] [805] [INFO] Sanic Extensions:
INFO:sanic.root:Sanic Extensions:
[2024-06-26 21:19:59 +0800] [805] [INFO]   > injection [0 dependencies; 0 constants]
INFO:sanic.root:  > injection [0 dependencies; 0 constants]
[2024-06-26 21:19:59 +0800] [805] [INFO]   > openapi [http://0.0.0.0:8777/docs]
INFO:sanic.root:  > openapi [http://0.0.0.0:8777/docs]
[2024-06-26 21:19:59 +0800] [805] [INFO]   > http
INFO:sanic.root:  > http
[2024-06-26 21:19:59 +0800] [805] [INFO]   > templating [jinja2==3.1.3]
INFO:sanic.root:  > templating [jinja2==3.1.3]
UPLOAD_ROOT_PATH: /workspace/qanything_local/QANY_DB/content
llm_api_serve_port: 7802
rerank_port: 9001
embed_port: 9001
<Logger debug_logger (INFO)> <Logger qa_logger (INFO)>
[2024-06-26 21:19:59 +0800] [813] [INFO] Sanic Extensions:
INFO:sanic.root:Sanic Extensions:
[2024-06-26 21:19:59 +0800] [813] [INFO]   > injection [0 dependencies; 0 constants]
INFO:sanic.root:  > injection [0 dependencies; 0 constants]
[2024-06-26 21:19:59 +0800] [813] [INFO]   > openapi [http://0.0.0.0:8777/docs]
INFO:sanic.root:  > openapi [http://0.0.0.0:8777/docs]
[2024-06-26 21:19:59 +0800] [813] [INFO]   > http
INFO:sanic.root:  > http
[2024-06-26 21:19:59 +0800] [813] [INFO]   > templating [jinja2==3.1.3]
INFO:sanic.root:  > templating [jinja2==3.1.3]
UPLOAD_ROOT_PATH: /workspace/qanything_local/QANY_DB/content
llm_api_serve_port: 7802
rerank_port: 9001
embed_port: 9001
<Logger debug_logger (INFO)> <Logger qa_logger (INFO)>
[2024-06-26 21:19:59 +0800] [811] [INFO] Sanic Extensions:
INFO:sanic.root:Sanic Extensions:
[2024-06-26 21:19:59 +0800] [811] [INFO]   > injection [0 dependencies; 0 constants]
INFO:sanic.root:  > injection [0 dependencies; 0 constants]
[2024-06-26 21:19:59 +0800] [811] [INFO]   > openapi [http://0.0.0.0:8777/docs]
INFO:sanic.root:  > openapi [http://0.0.0.0:8777/docs]
[2024-06-26 21:19:59 +0800] [811] [INFO]   > http
INFO:sanic.root:  > http
[2024-06-26 21:19:59 +0800] [811] [INFO]   > templating [jinja2==3.1.3]
INFO:sanic.root:  > templating [jinja2==3.1.3]
UPLOAD_ROOT_PATH: /workspace/qanything_local/QANY_DB/content
llm_api_serve_port: 7802
rerank_port: 9001
embed_port: 9001
<Logger debug_logger (INFO)> <Logger qa_logger (INFO)>
[2024-06-26 21:19:59 +0800] [810] [INFO] Sanic Extensions:
INFO:sanic.root:Sanic Extensions:
[2024-06-26 21:19:59 +0800] [810] [INFO]   > injection [0 dependencies; 0 constants]
INFO:sanic.root:  > injection [0 dependencies; 0 constants]
[2024-06-26 21:19:59 +0800] [810] [INFO]   > openapi [http://0.0.0.0:8777/docs]
INFO:sanic.root:  > openapi [http://0.0.0.0:8777/docs]
[2024-06-26 21:19:59 +0800] [810] [INFO]   > http
INFO:sanic.root:  > http
[2024-06-26 21:19:59 +0800] [810] [INFO]   > templating [jinja2==3.1.3]
INFO:sanic.root:  > templating [jinja2==3.1.3]
UPLOAD_ROOT_PATH: /workspace/qanything_local/QANY_DB/content
llm_api_serve_port: 7802
rerank_port: 9001
embed_port: 9001
<Logger debug_logger (INFO)> <Logger qa_logger (INFO)>
[2024-06-26 21:19:59 +0800] [812] [INFO] Sanic Extensions:
INFO:sanic.root:Sanic Extensions:
[2024-06-26 21:19:59 +0800] [812] [INFO]   > injection [0 dependencies; 0 constants]
INFO:sanic.root:  > injection [0 dependencies; 0 constants]
[2024-06-26 21:19:59 +0800] [812] [INFO]   > openapi [http://0.0.0.0:8777/docs]
INFO:sanic.root:  > openapi [http://0.0.0.0:8777/docs]
[2024-06-26 21:19:59 +0800] [812] [INFO]   > http
INFO:sanic.root:  > http
[2024-06-26 21:19:59 +0800] [812] [INFO]   > templating [jinja2==3.1.3]
INFO:sanic.root:  > templating [jinja2==3.1.3]
INFO:debug_logger:[SUCCESS] 数据库qanything检查通过
INFO:debug_logger:[SUCCESS] 数据库qanything检查通过
INFO:debug_logger:[SUCCESS] 数据库qanything检查通过
INFO:debug_logger:[SUCCESS] 数据库qanything检查通过
INFO:debug_logger:[SUCCESS] 数据库qanything检查通过
INFO:debug_logger:[SUCCESS] 数据库qanything检查通过
INFO:debug_logger:[SUCCESS] 数据库qanything检查通过
INFO:debug_logger:[SUCCESS] 数据库qanything检查通过
INFO:debug_logger:ADD COLUMN timestamp
INFO:debug_logger:ADD COLUMN timestamp
INFO:debug_logger:ADD COLUMN timestamp
INFO:debug_logger:ADD COLUMN timestamp
INFO:debug_logger:ADD COLUMN timestamp
INFO:debug_logger:1060 (42S21): Duplicate column name 'timestamp'
INFO:debug_logger:[SUCCESS] 数据库qanything连接成功
init local_doc_qa in local
INFO:debug_logger:1060 (42S21): Duplicate column name 'timestamp'
INFO:debug_logger:[SUCCESS] 数据库qanything连接成功
init local_doc_qa in local
INFO:debug_logger:1060 (42S21): Duplicate column name 'timestamp'
INFO:debug_logger:ADD COLUMN timestamp
INFO:debug_logger:[SUCCESS] 数据库qanything连接成功
init local_doc_qa in local
INFO:debug_logger:1060 (42S21): Duplicate column name 'timestamp'
INFO:debug_logger:[SUCCESS] 数据库qanything连接成功
init local_doc_qa in local
INFO:debug_logger:1060 (42S21): Duplicate column name 'timestamp'
INFO:debug_logger:[SUCCESS] 数据库qanything连接成功
init local_doc_qa in local
INFO:debug_logger:1060 (42S21): Duplicate column name 'timestamp'
INFO:debug_logger:[SUCCESS] 数据库qanything连接成功
init local_doc_qa in local
INFO:debug_logger:[SUCCESS] 数据库qanything检查通过
INFO:debug_logger:ADD COLUMN timestamp
INFO:debug_logger:1060 (42S21): Duplicate column name 'timestamp'
INFO:debug_logger:[SUCCESS] 数据库qanything连接成功
init local_doc_qa in local
INFO:debug_logger:[SUCCESS] 数据库qanything检查通过
INFO:debug_logger:ADD COLUMN timestamp
INFO:debug_logger:1060 (42S21): Duplicate column name 'timestamp'
INFO:debug_logger:[SUCCESS] 数据库qanything连接成功
init local_doc_qa in local
INFO:debug_logger:ADD COLUMN timestamp
INFO:debug_logger:1060 (42S21): Duplicate column name 'timestamp'
INFO:debug_logger:[SUCCESS] 数据库qanything连接成功
init local_doc_qa in local
INFO:debug_logger:ADD COLUMN timestamp
INFO:debug_logger:1060 (42S21): Duplicate column name 'timestamp'
INFO:debug_logger:[SUCCESS] 数据库qanything连接成功
init local_doc_qa in local
[2024-06-26 21:20:00 +0800] [806] [INFO] Starting worker [806]
INFO:sanic.server:Starting worker [806]
[2024-06-26 21:20:00 +0800] [814] [INFO] Starting worker [814]
INFO:sanic.server:Starting worker [814]
[2024-06-26 21:20:00 +0800] [809] [INFO] Starting worker [809]
INFO:sanic.server:Starting worker [809]
[2024-06-26 21:20:00 +0800] [813] [INFO] Starting worker [813]
INFO:sanic.server:Starting worker [813]
[2024-06-26 21:20:00 +0800] [807] [INFO] Starting worker [807]
INFO:sanic.server:Starting worker [807]
[2024-06-26 21:20:00 +0800] [805] [INFO] Starting worker [805]
INFO:sanic.server:Starting worker [805]
[2024-06-26 21:20:00 +0800] [811] [INFO] Starting worker [811]
INFO:sanic.server:Starting worker [811]
[2024-06-26 21:20:00 +0800] [808] [INFO] Starting worker [808]
INFO:sanic.server:Starting worker [808]
[2024-06-26 21:20:00 +0800] [812] [INFO] Starting worker [812]
INFO:sanic.server:Starting worker [812]
[2024-06-26 21:20:00 +0800] [810] [INFO] Starting worker [810]
INFO:sanic.server:Starting worker [810]

### 备注 | Anything else?

![图片1](https://github.com/netease-youdao/QAnything/assets/103884644/b1aef2bb-89b0-4ded-8bd1-8cd571da4aea)

**Comment by ikun-moxiaofei** [comment]
有可能是显存不够了，换一个小一点的模型试一试

**Comment by yyinchan** [comment]
> 有可能是显存不够了，换一个小一点的模型试一试

换了MiniChat-2-3B前端还是这样呢:：😭


qanything-container-local  | Waiting for the backend service to start...
qanything-container-local  | 等待启动后端服务
qanything-container-local  | The qanything backend service is ready! (4/8)
qanything-container-local  | qanything后端服务已就绪! (4/8)
qanything-container-local  | Dependencies related to npm are obtained. (5/8)
qanything-container-local  | The front_end/dist folder already exists, no need to build the front end again.(6/8)
qanything-container-local  | Waiting for the front-end service to start...
qanything-container-local  | 等待启动前端服务
qanything-container-local  | 
qanything-container-local  | > ai-demo@1.0.1 serve
qanything-container-local  | > vite preview --port 5052
qanything-container-local  | 
qanything-container-local  | The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more detai
ls.
qanything-container-local  | Waiting for the front-end service to start...
qanything-container-local  | 等待启动前端服务
qanything-container-local  |   ➜  Local:   http://localhost:5052/qanything
qanything-container-local  |   ➜  Network: http://172.23.0.6:5052/qanything
qanything-container-local  | The front-end service is ready!...(7/8)
qanything-container-local  | 前端服务已就绪!...(7/8)
qanything-container-local  | I0627 09:49:51.784766 134 grpc_server.cc:377] Thread started for CommonHandler
qanything-container-local  | I0627 09:49:51.784984 134 infer_handler.cc:629] New request handler for ModelInferHandler, 0
qanything-container-local  | I0627 09:49:51.785061 134 infer_handler.h:1025] Thread started for ModelInferHandler
qanything-container-local  | I0627 09:49:51.785223 134 infer_handler.cc:629] New request handler for ModelInferHandler, 0
qanything-container-local  | I0627 09:49:51.785266 134 infer_handler.h:1025] Thread started for ModelInferHandler
qanything-container-local  | I0627 09:49:51.785448 134 stream_infer_handler.cc:122] New request handler for ModelStreamInferHandler, 0
qanything-container-local  | I0627 09:49:51.785507 134 infer_handler.h:1025] Thread started for ModelStreamInferHandler
qanything-container-local  | I0627 09:49:51.785531 134 grpc_server.cc:2450] Started GRPCInferenceService at 0.0.0.0:9001
qanything-container-local  | I0627 09:49:51.786020 134 http_server.cc:3555] Started HTTPService at 0.0.0.0:9000
qanything-container-local  | I0627 09:49:51.827605 134 http_server.cc:185] Started Metrics Service at 0.0.0.0:9002
qanything-container-local  | I0627 09:50:46.967427 134 http_server.cc:3449] HTTP request: 0 /v2/health/ready
qanything-container-local  | The embedding and rerank service is ready!. (7.5/8)
qanything-container-local  | Embedding 和 Rerank 服务已准备就绪！(7.5/8)
qanything-container-local  | You are using the default legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
  0%|          | 0/1 [00:00<?, ?it/s]27 17:50:06 | ERROR | stderr |
100%|██████████| 1/1 [00:38<00:00, 38.79s/it]:45 | ERROR | stderr |
100%|██████████| 1/1 [00:38<00:00, 38.79s/it]:45 | ERROR | stderr |
qanything-container-local  | 2024-06-27 17:50:45 | ERROR | stderr |
qanything-container-local  | 2024-06-27 17:50:45 | INFO | model_worker | Register to controller
qanything-container-local  | 2024-06-27 17:50:45 | ERROR | stderr | INFO:     Started server process [148]
qanything-container-local  | 2024-06-27 17:50:45 | ERROR | stderr | INFO:     Waiting for application startup.
qanything-container-local  | 2024-06-27 17:50:45 | ERROR | stderr | INFO:     Application startup complete.
qanything-container-local  | 2024-06-27 17:50:45 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:7801 (Press CTRL+C to quit)
qanything-container-local  |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
qanything-container-local  |                                  Dload  Upload   Total   Spent    Left  Speed
100    28  100    28    0     0  14042      0 --:--:-- --:--:-- --:--:-- 28000
qanything-container-local  | The llm service is ready!, now you can use the qanything service. (8/8)
qanything-container-local  | LLM 服务已准备就绪！现在您可以使用qanything服务。（8/8)
qanything-container-local  | 开始检查日志文件中的错误信息...
qanything-container-local  | /workspace/qanything_local/logs/debug_logs/rerank_server.log 中未检测到明确的错误信息。请手动排查 /workspace/qanything_local/logs/debug_logs/rerank_server.log 以获取更多信息。
qanything-container-local  | /workspace/qanything_local/logs/debug_logs/ocr_server.log 中未检测到明确的错误信息。请手动排查 /workspace/qanything_local/logs/debug_logs/ocr_server.log 以获取更多信息。
qanything-container-local  | /workspace/qanything_local/logs/debug_logs/sanic_api.log 中未检测到明确的错误信息。请手动排查 /workspace/qanything_local/logs/debug_logs/sanic_api.log 以获取更多信息。
qanything-container-local  | Time elapsed: 59 seconds.
qanything-container-local  | 已耗时: 59 秒.
qanything-container-local  | Please visit the front-end service at [http://localhost:5052/qanything/] to conduct Q&A.
qanything-container-local  | 请在[http://localhost:5052/qanything/]下访问前端服务来进行问答，如果前端报错，请在浏览器按F12以获取更多报错信息

**Comment by HuangListen** [comment]
和你一样，看日志sanic_api.log的文件有具体原因，端口混合检索端口有问题，我还没具体研究
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "handle_request", line 97, in handle_request
  File "/workspace/qanything_local/qanything_kernel/qanything_server/handler.py", line 35, in new_knowledge_base
    local_doc_qa.create_milvus_collection(user_id, kb_id, kb_name)
  File "/workspace/qanything_local/qanything_kernel/core/local_doc_qa.py", line 57, in create_milvus_collection
    milvus_kb = MilvusClient(self.mode, user_id, [kb_id])
  File "/workspace/qanything_local/qanything_kernel/connector/database/milvus/milvus_client.py", line 56, in __init__
    self.client = ElasticsearchClient(index_name=self.index_name)
  File "/workspace/qanything_local/qanything_kernel/connector/database/milvus/es_client.py", line 73, in __init__
    raise RuntimeError(f"Elasticsearch client initialization failed: {e}\nConnection setup: {connects}")
RuntimeError: Elasticsearch client initialization failed: Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7fdfaa93a6e0>: Failed to resolve 'es-container-local' ([Errno -3] Temporary failure in name resolution)))
Connection setup: {'hosts': 'http://es-container-local:9200/'}

**Comment by stellaludai** [comment]
我遇到了一样的问题，发现是host+api配置的问题。在front_end/.env.production里VITE_APP_API_HOST改成http://localhost:8777/api，.env里user_ip改成localhost, 然后run_for_local_option.sh里也改对应的部分就好了
