### ISSUE TITLE
网址解析不了

### ISSUE THREAD

**Issue by xinxin12345** [netease-youdao/QAnything#434]
我在使用master代码 采用docker部署之后，网址解析不了，sanic_api.log中日志如下

INFO:debug_logger:##ES## - success to connect to {'name': '916112ef1d24', 'cluster_name': 'docker-cluster', 'cluster_uuid': 'ibt4LSMlQXCrU2FlI7u6PA', 'version': {'number': '8.11.4', 'build_flavor': 'default', 'build_type': 'docker', 'build_hash': 'da06c53fd49b7e676ccf8a32d6655c5155c16d81', 'build_date': '2024-01-08T10:05:08.438562403Z', 'build_snapshot': False, 'lucene_version': '9.8.0', 'minimum_wire_compatibility_version': '7.17.0', 'minimum_index_compatibility_version': '7.0.0'}, 'tagline': 'You Know, for Search'}
INFO:debug_logger:check_user_exist [('zzp',)]
INFO:debug_logger:list_kbs zzp
INFO:debug_logger:all kb infos: [{'kb_id': 'KB40a239a96b1d497e82d1230912231567', 'kb_name': 'test'}]
INFO:debug_logger:list_docs zzp
INFO:debug_logger:kb_id: KB40a239a96b1d497e82d1230912231567
INFO:debug_logger:upload_weblink zzp
INFO:debug_logger:check_kb_exist [('KB40a239a96b1d497e82d1230912231567',)]
INFO:debug_logger:check_user_exist [('zzp',)]
INFO:debug_logger:check_kb_exist [('KB40a239a96b1d497e82d1230912231567',)]
INFO:debug_logger:add_file: 13a88d8f42324a8cb15a217ea12182a5
INFO:debug_logger:success init localfile https://perfxlab.com/
INFO:debug_logger:insert_files_to_milvus: KB40a239a96b1d497e82d1230912231567
INFO:debug_logger:match milvus_client: <qanything_kernel.connector.database.milvus.milvus_client.MilvusClient object at 0x7f80052fdcf0>
INFO:debug_logger:load url: https://perfxlab.com/
INFO:langchain_community.document_loaders.web_base:fake_useragent not found, using default user agent.To get a realistic header for requests, `pip install fake_useragent`.
INFO:langchain_community.document_loaders.web_base:fake_useragent not found, using default user agent.To get a realistic header for requests, `pip install fake_useragent`.
INFO:langchain_community.document_loaders.web_base:fake_useragent not found, using default user agent.To get a realistic header for requests, `pip install fake_useragent`.
INFO:debug_logger:list_kbs zzp
INFO:debug_logger:all kb infos: [{'kb_id': 'KB40a239a96b1d497e82d1230912231567', 'kb_name': 'test'}]
INFO:langchain_community.document_loaders.web_base:fake_useragent not found, using default user agent.To get a realistic header for requests, `pip install fake_useragent`.
INFO:debug_logger:list_docs zzp
INFO:debug_logger:kb_id: KB40a239a96b1d497e82d1230912231567
INFO:langchain_community.document_loaders.web_base:fake_useragent not found, using default user agent.To get a realistic header for requests, `pip install fake_useragent`.
INFO:debug_logger:list_docs zzp
INFO:debug_logger:kb_id: KB40a239a96b1d497e82d1230912231567
ERROR:debug_logger:split error: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/qanything_local/qanything_kernel/core/local_doc_qa.py", line 80, in insert_files_to_milvus
    local_file.split_file_to_docs(self.get_ocr_result)
  File "/workspace/qanything_local/qanything_kernel/core/local_file.py", line 64, in split_file_to_docs
    docs = loader.load_and_split(text_splitter=textsplitter)
  File "/usr/local/lib/python3.10/dist-packages/langchain_community/document_loaders/base.py", line 50, in load_and_split
    docs = self.load()
  File "/workspace/qanything_local/qanything_kernel/utils/loader/my_recursive_url_loader.py", line 91, in load
    return list(self.lazy_load())
  File "/workspace/qanything_local/qanything_kernel/utils/loader/my_recursive_url_loader.py", line 78, in get_child_links_recursive
    yield from WebBaseLoader(link).load()
  File "/usr/local/lib/python3.10/dist-packages/langchain_community/document_loaders/web_base.py", line 255, in load
    return list(self.lazy_load())
  File "/usr/local/lib/python3.10/dist-packages/langchain_community/document_loaders/web_base.py", line 248, in lazy_load
    soup = self._scrape(path, bs_kwargs=self.bs_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/langchain_community/document_loaders/web_base.py", line 227, in _scrape
    html_doc = self.session.get(url, **self.requests_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

请问这是什么原因呢

**Comment by xixihahaliu** [comment]
langchain解析url缺少一个库，需要去容器里执行pip install fake_useragent安装一下，下周将会更新v2.0版本，这个问题将一并解决

**Comment by xinxin12345** [comment]
> 看log可能存在两个问题，一个是docker容器无法连接外网（解析url需要连接到外网），另一个是目标url可能存在防爬虫机制，下周将更新v2.0版本，可以重新尝试下

好的，感谢！
