### ISSUE TITLE
[BUG] Upload file and parse error

### ISSUE THREAD

**Issue by liuxiaocs7** [netease-youdao/QAnything#47]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

```
2024-01-22 11:07:18,232 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-6' coro=<LocalDocQA.insert_files_to_milvus() done, defined at /workspace/qanything_local/qanything_kernel/core/local_doc_qa.py:89> exception=AttributeError("'NoneType' object has no attribute 'schema'")>
Traceback (most recent call last):
  File "/workspace/qanything_local/qanything_kernel/core/local_doc_qa.py", line 123, in insert_files_to_milvus
    ret = await milvus_kv.insert_files(local_file.file_id, local_file.file_name, local_file.file_path,
  File "/workspace/qanything_local/qanything_kernel/connector/database/milvus/milvus_client.py", line 136, in insert_files
    data = [[] for _ in range(len(self.sess.schema))]
AttributeError: 'NoneType' object has no attribute 'schema'

```

### 运行环境 | Environment

```Markdown
- OS:
- NVIDIA Driver:
- CUDA:
- Docker Compose:
- NVIDIA GPU Memory:
```

**Comment by nongmo677** [comment]
检查milvus是否正确启动，并且是否能使用python milvus_client 进行连接，有时候也可能存在python milvus client与milvus不兼容的情况，可以根据QAnything提供的requirements.txt和docker-compose.yaml进行对应
