### ISSUE TITLE
内网环境进行对话时报错Connection to openaipublic.blob.core.windows.net timed out

### ISSUE THREAD

**Issue by lijiaqi0121** [netease-youdao/QAnything#472]
在内网环境，使用python安装的方式，成功启动服务之后，进行对话时报错
报错信息：
`requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2777dd30d0>, 'Connection to openaipublic.blob.core.windows.net timed out. (connect timeout=None)'))`
请问要怎么解决

**Comment by charleshuangruo** [comment]
> 在内网环境，使用python安装的方式，成功启动服务之后，进行对话时报错 报错信息： `requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2777dd30d0>, 'Connection to openaipublic.blob.core.windows.net timed out. (connect timeout=None)'))` 请问要怎么解决

同问，已经选择了用自己的GPU，仍然访问openai的接口，还访问超时，无法正常启动后端服务。是否有访问openai接口的必要？

**Comment by lijiaqi0121** [comment]
> > 在内网环境，使用python安装的方式，成功启动服务之后，进行对话时报错 报错信息： `requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2777dd30d0>, 'Connection to openaipublic.blob.core.windows.net timed out. (connect timeout=None)'))` 请问要怎么解决
> 
> 同问，已经选择了用自己的GPU，仍然访问openai的接口，还访问超时，无法正常启动后端服务。是否有访问openai接口的必要？

我当时是本地下载了/encodings/cl100k_base.tiktoken，然后修改了`/root/anaconda3/lib/python3.11/site-packages/tiktoken_ext/openai_public.py`这个文件，把/encodings/cl100k_base.tiktoken换成了本地下载的地址
```
def cl100k_base():
    #https://openaipublic.blob.core.windows.net/encodings/cl100k_base.tiktoken
    mergeable_ranks = load_tiktoken_bpe(
        "/home/QAnything/cl100k_base.tiktoken",
        expected_hash="223921b76ee99bde995b7ff738513eef100fb51d18c93597a113bcffe865b2a7",
    )
```

**Comment by charleshuangruo** [comment]
> > > 在内网环境，使用python安装的方式，成功启动服务之后，进行对话时报错 报错信息： `requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2777dd30d0>, 'Connection to openaipublic.blob.core.windows.net timed out. (connect timeout=None)'))` 请问要怎么解决
> > 
> > 
> > 同问，已经选择了用自己的GPU，仍然访问openai的接口，还访问超时，无法正常启动后端服务。是否有访问openai接口的必要？
> 
> 我当时是本地下载了/encodings/cl100k_base.tiktoken，然后修改了`/root/anaconda3/lib/python3.11/site-packages/tiktoken_ext/openai_public.py`这个文件，把/encodings/cl100k_base.tiktoken换成了本地下载的地址
> 
> ```
> def cl100k_base():
>     #https://openaipublic.blob.core.windows.net/encodings/cl100k_base.tiktoken
>     mergeable_ranks = load_tiktoken_bpe(
>         "/home/QAnything/cl100k_base.tiktoken",
>         expected_hash="223921b76ee99bde995b7ff738513eef100fb51d18c93597a113bcffe865b2a7",
>     )
> ```

好的，我照您说的做了，现在报新的错。blobfile也用pip安装不上：
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/qanything-python/lib/python3.10/site-packages/tiktoken/load.py", line 17, in read_file
    import blobfile
ModuleNotFoundError: No module named 'blobfile'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/qanything-python/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/anaconda3/envs/qanything-python/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/QAnything/qanything_kernel/qanything_server/sanic_api.py", line 164, in <module>
    from .handler import *
  File "/usr/local/QAnything/qanything_kernel/qanything_server/handler.py", line 1, in <module>
    from qanything_kernel.core.local_file import LocalFile
  File "/usr/local/QAnything/qanything_kernel/core/local_file.py", line 5, in <module>
    from qanything_kernel.utils.loader.my_recursive_url_loader import MyRecursiveUrlLoader
  File "/usr/local/QAnything/qanything_kernel/utils/loader/__init__.py", line 4, in <module>
    from .self_pdf_loader import PdfLoader
  File "/usr/local/QAnything/qanything_kernel/utils/loader/self_pdf_loader.py", line 3, in <module>
    from qanything_kernel.utils.loader.pdf_to_markdown.core.parser import PdfParser
  File "/usr/local/QAnything/qanything_kernel/utils/loader/pdf_to_markdown/core/parser/__init__.py", line 3, in <module>
    from .pdf_parser import HuParser as PdfParser, PlainParser
  File "/usr/local/QAnything/qanything_kernel/utils/loader/pdf_to_markdown/core/parser/pdf_parser.py", line 18, in <module>
    from qanything_kernel.utils.loader.pdf_to_markdown.core.nlp import huqie
  File "/usr/local/QAnything/qanything_kernel/utils/loader/pdf_to_markdown/core/nlp/__init__.py", line 9, in <module>
    encoder = tiktoken.encoding_for_model("gpt-3.5-turbo")
  File "/usr/local/anaconda3/envs/qanything-python/lib/python3.10/site-packages/tiktoken/model.py", line 101, in encoding_for_model
    return get_encoding(encoding_name_for_model(model_name))
  File "/usr/local/anaconda3/envs/qanything-python/lib/python3.10/site-packages/tiktoken/registry.py", line 73, in get_encoding
    enc = Encoding(**constructor())
  File "/usr/local/anaconda3/envs/qanything-python/lib/python3.10/site-packages/tiktoken_ext/openai_public.py", line 76, in cl100k_base
    mergeable_ranks = load_tiktoken_bpe(
  File "/usr/local/anaconda3/envs/qanything-python/lib/python3.10/site-packages/tiktoken/load.py", line 147, in load_tiktoken_bpe
    contents = read_file_cached(tiktoken_bpe_file, expected_hash)
  File "/usr/local/anaconda3/envs/qanything-python/lib/python3.10/site-packages/tiktoken/load.py", line 64, in read_file_cached
    contents = read_file(blobpath)
  File "/usr/local/anaconda3/envs/qanything-python/lib/python3.10/site-packages/tiktoken/load.py", line 19, in read_file
    raise ImportError(
ImportError: blobfile is not installed. Please install it by running `pip install blobfile`.

**Comment by lijiaqi0121** [comment]
为什么安装不上，有报错信息吗？

**Comment by charleshuangruo** [comment]
> 为什么安装不上，有报错信息吗？

可能是网络不通的问题（一直连着vpn），说版本不匹配，但是前面说网络不通：
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7ff8c2798f70>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /simple/blobfile/
ERROR: Could not find a version that satisfies the requirement blobfile (from versions: none)
ERROR: No matching distribution found for blobfile

我现在看到有blobfile的git（https://github.com/blobfile/blobfile），想下载源码进行本地安装（pip install -e .），正在测试，安装得比较慢，不知道什么原因：
Installing build dependencies ... \

**Comment by charleshuangruo** [comment]
> > > 在内网环境，使用python安装的方式，成功启动服务之后，进行对话时报错 报错信息： `requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f2777dd30d0>, 'Connection to openaipublic.blob.core.windows.net timed out. (connect timeout=None)'))` 请问要怎么解决
> > 
> > 
> > 同问，已经选择了用自己的GPU，仍然访问openai的接口，还访问超时，无法正常启动后端服务。是否有访问openai接口的必要？
> 
> 我当时是本地下载了/encodings/cl100k_base.tiktoken，然后修改了`/root/anaconda3/lib/python3.11/site-packages/tiktoken_ext/openai_public.py`这个文件，把/encodings/cl100k_base.tiktoken换成了本地下载的地址
> 
> ```
> def cl100k_base():
>     #https://openaipublic.blob.core.windows.net/encodings/cl100k_base.tiktoken
>     mergeable_ranks = load_tiktoken_bpe(
>         "/home/QAnything/cl100k_base.tiktoken",
>         expected_hash="223921b76ee99bde995b7ff738513eef100fb51d18c93597a113bcffe865b2a7",
>     )
> ```

多谢，已经解决了，把wsl设置成可以使用windows的vpn了，就可以安装上blobfile依赖了。已运行成功
