### ISSUE TITLE
2.0通过mac安装，一直启动失败。

### ISSUE THREAD

**Issue by newsyh** [netease-youdao/QAnything#496]
设备：mac
芯片：M2
启动失败，一直提示
2024-09-06 11:23:20 Waiting for the backend service to start...
2024-09-06 11:23:20 等待启动后端服务
最终启动失败：
[2024-09-06 03:23:52 +0000] [291] [INFO] Sanic Extensions:
2024-09-06 11:26:16 [2024-09-06 03:23:52 +0000] [291] [INFO]   > injection [0 dependencies; 0 constants]
2024-09-06 11:26:16 [2024-09-06 03:23:52 +0000] [291] [INFO]   > openapi [http://0.0.0.0:8777/docs]
2024-09-06 11:26:16 [2024-09-06 03:23:52 +0000] [291] [INFO]   > http 
2024-09-06 11:26:16 [2024-09-06 03:23:52 +0000] [291] [INFO]   > templating [jinja2==3.1.4]
2024-09-06 11:26:16 [2024-09-06 03:23:55 +0000] [291] [ERROR] Connection error caused by: ConnectionError(Connection error caused by: ProtocolError(('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))))
2024-09-06 11:26:16 Traceback (most recent call last):
2024-09-06 11:26:16   File "/usr/local/lib/python3.10/site-packages/sanic/worker/serve.py", line 117, in worker_serve
2024-09-06 11:26:16     return _serve_http_1(
2024-09-06 11:26:16   File "/usr/local/lib/python3.10/site-packages/sanic/server/runners.py", line 223, in _serve_http_1
2024-09-06 11:26:16     loop.run_until_complete(app._server_event("init", "before"))
2024-09-06 11:26:16 --
2024-09-06 11:26:16     meta, resp_body = self.transport.perform_request(
2024-09-06 11:26:16   File "/usr/local/lib/python3.10/site-packages/elastic_transport/_transport.py", line 342, in perform_request
2024-09-06 11:26:16     resp = node.perform_request(
2024-09-06 11:26:16   File "/usr/local/lib/python3.10/site-packages/elastic_transport/_node/_http_urllib3.py", line 202, in perform_request
2024-09-06 11:26:16     raise err from None
2024-09-06 11:26:16 elastic_transport.ConnectionError: Connection error caused by: ConnectionError(Connection error caused by: ProtocolError(('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))))
2024-09-06 11:26:16 [2024-09-06 03:23:55 +0000] [13] [ERROR] Not all workers acknowledged a successful startup. Shutting down.
2024-09-06 11:26:16 
2024-09-06 11:26:16 One of your worker processes terminated before startup was completed. Please solve any errors experienced during startup. If you do not see an exception traceback in your error logs, try running Sanic in in a single process using --single-process or single_process=True. Once you are confident that the server is able to start without errors you can switch back to multiprocess mode.
2024-09-06 11:26:16 [2024-09-06 03:23:55 +0000] [13] [INFO] Killing Sanic-Server-0-0 [291]
2024-09-06 11:26:16 [2024-09-06 03:23:55 +0000] [13] [INFO] Server Stopped
2024-09-06 11:26:16 检测到错误信息，请查看上面的输出。

请问是什么原因

<img width="1035" alt="image" src="https://github.com/user-attachments/assets/fa2a8750-a2e4-431a-8ecd-c8c5f15f71a9">
![WX20240906-115548@2x](https://github.com/user-attachments/assets/9b23031f-7b92-4562-b98d-7c59b5233e76)

**Comment by sun-kaiming** [comment]
同问

**Comment by sunguangran** [comment]
+1

**Comment by whiletrue2009** [comment]
+1 
设备：macbook pro
芯片：M1


 下面的三个条件都满足了
<img width="413" alt="image" src="https://github.com/user-attachments/assets/395c49b7-6dd9-4770-b1f0-06c4db3ed851">


<img width="1785" alt="image" src="https://github.com/user-attachments/assets/81c7fb79-b352-4c58-a258-b61e40ef7598">

**Comment by EchoWht** [comment]
+1 
![image](https://github.com/user-attachments/assets/33a904fb-9d5d-47d3-ab92-6f799681fb5f)

**Comment by liang-xian** [comment]
设备：macbook pro
芯片：M1
把 docker-compose-mac.yaml 中的host.docker.internal 改成172.17.0.1 可以启动起来了
![image](https://github.com/user-attachments/assets/72976cd0-abf5-4459-8064-b934dd8e7971)

**Comment by SongXinbai** [comment]
感觉是内存问题，我遇到了同样的问题，ES启动失败题时exit code 137，把Docker Desktop的内存限制调整为16GB后就启动成功了

**Comment by wangjv2004** [comment]
> 设备：macbook pro 芯片：M1 把 docker-compose-mac.yaml 中的host.docker.internal 改成172.17.0.1 可以启动起来了 ![image](https://github.com/user-attachments/assets/72976cd0-abf5-4459-8064-b934dd8e7971)

不行啊，还是同样的问题。你MAC的内存多大？

**Comment by wangjv2004** [comment]
> 感觉是内存问题，我遇到了同样的问题，ES启动失败题时exit code 137，把Docker Desktop的内存限制调整为16GB后就启动成功了

我MAC32GB内存，docker desltop中设置，给了20GB，甚至32GB全给，但还是不行。在系统上看MAC的内存使用率只有不到70%，docker上Container memory usage也没有超过10GB。感觉给了，但它不用啊

**Comment by wangjv2004** [comment]
qanything-container-local  | Waiting for the backend service to start...
qanything-container-local  | 等待启动后端服务
qanything-container-local  | Waiting for the backend service to start...
qanything-container-local  | 等待启动后端服务
qanything-container-local  | 启动后端服务超时，自动检查日志文件 /workspace/QAnything/logs/debug_logs/main_server.log：
**qanything-container-local  | /workspace/QAnything/logs/debug_logs/main_server.log 中未检测到明确的错误信息。请手动排查 /workspace/QAnything/logs/debug_logs/main_server.log 以获取更多信息。
qanything-container-local exited with code 1**

**Comment by wangjv2004** [comment]
终于解决了！！！

1. 在entrypoint.sh中，增加超时到1800，多给点时间让启动。就是那个if [ $elapsed_time -ge 1800 ]; then。如下：

<img width="998" alt="Image" src="https://github.com/user-attachments/assets/78c86a92-e47b-42b9-b234-15e5872a9531" />
	
	
2. 在docker-compose-mac.yaml中，增大共享主机内存，就是那个shm_size: '16gb'，如下：

<img width="838" alt="Image" src="https://github.com/user-attachments/assets/a3e151a3-6eb6-47a2-bae4-074ea5318de0" />
