### ISSUE TITLE
[BUG] 启动不了。一直等待启动后端服务。win和linux都是

### ISSUE THREAD

**Issue by jacktpy** [netease-youdao/QAnything#517]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

使用docker-compose -f docker-compose-win.yaml up
docker-compose -f docker-compose-linux.yaml up 启动都有问题，首先mysql会报没有远程访问权限，手动连接给权限后又会一直等待启动后端服务。

### 期望行为 | Expected Behavior

正常启动。

### 运行环境 | Environment

```Markdown
- OS:Windows 11 WSL2
- NVIDIA Driver:
- CUDA:12.3
- Docker Compose:27.2.0
- NVIDIA GPU Memory: 16G
```

### QAnything日志 | QAnything logs

UPLOAD_ROOT_PATH: /workspace/QAnything/QANY_DB/content
IMAGES_ROOT_PATH: /workspace/QAnything/qanything_kernel/qanything_server/dist/qanything/assets/file_images
<Logger debug_logger (INFO)> <Logger qa_logger (INFO)> <Logger rerank_logger (INFO)> <Logger embed_logger (INFO)> <Logger insert_logger (INFO)>
functions:[{'name': 'duckduckgo_search', 'description': 'duckduckgo_search(query: str, top_k: int) - Search infomation on internet. Useful for when the context can not answer the question. Input should be a search query.', 'parameters': {'type': 'object', 'properties': {'query': {'description': 'search query', 'type': 'string'}}, 'required': ['query']}}]
[2024-09-11 10:45:03 +0000] [494] [INFO] Sanic Extensions:
[2024-09-11 10:45:03 +0000] [494] [INFO]   > injection [0 dependencies; 0 constants]
[2024-09-11 10:45:03 +0000] [494] [INFO]   > openapi [http://0.0.0.0:8777/docs]
[2024-09-11 10:45:03 +0000] [494] [INFO]   > http 
[2024-09-11 10:45:03 +0000] [494] [INFO]   > templating [jinja2==3.1.4]
Failed to create new connection using: fa696811251e45e7862c2521b6664714
[2024-09-11 10:45:20 +0000] [494] [ERROR] <MilvusException: (code=2, message=Fail connecting to server on host.docker.internal:19540. Timeout)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 143, in _wait_for_channel_ready
    grpc.channel_ready_future(self._channel).result(timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/grpc/_utilities.py", line 162, in result
    self._block(timeout)
  File "/usr/local/lib/python3.10/site-packages/grpc/_utilities.py", line 106, in _block
    raise grpc.FutureTimeoutError()
grpc.FutureTimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/sanic/worker/serve.py", line 117, in worker_serve
    return _serve_http_1(
  File "/usr/local/lib/python3.10/site-packages/sanic/server/runners.py", line 223, in _serve_http_1
    loop.run_until_complete(app._server_event("init", "before"))
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.10/site-packages/sanic/app.py", line 1764, in _server_event
    await self.dispatch(
  File "/usr/local/lib/python3.10/site-packages/sanic/signals.py", line 208, in dispatch
    return await dispatch
  File "/usr/local/lib/python3.10/site-packages/sanic/signals.py", line 183, in _dispatch
    raise e
  File "/usr/local/lib/python3.10/site-packages/sanic/signals.py", line 167, in _dispatch
    retval = await maybe_coroutine
  File "/usr/local/lib/python3.10/site-packages/sanic/app.py", line 1315, in _listener
    await maybe_coro
  File "/workspace/QAnything/qanything_kernel/qanything_server/sanic_api.py", line 53, in init_local_doc_qa
    local_doc_qa.init_cfg(args)
  File "/workspace/QAnything/qanything_kernel/core/local_doc_qa.py", line 73, in init_cfg
    self.milvus_kb = VectorStoreMilvusClient()
  File "/workspace/QAnything/qanything_kernel/core/retriever/vectorstore.py", line 270, in __init__
    self.local_vectorstore: Milvus = SelfMilvus(
  File "/workspace/QAnything/qanything_kernel/core/retriever/vectorstore.py", line 16, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/langchain_community/vectorstores/milvus.py", line 200, in __init__
    self.alias = self._create_connection_alias(connection_args)
  File "/usr/local/lib/python3.10/site-packages/langchain_community/vectorstores/milvus.py", line 283, in _create_connection_alias
    raise e
  File "/usr/local/lib/python3.10/site-packages/langchain_community/vectorstores/milvus.py", line 278, in _create_connection_alias
    connections.connect(alias=alias, **connection_args)
  File "/usr/local/lib/python3.10/site-packages/pymilvus/orm/connections.py", line 414, in connect
    connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
  File "/usr/local/lib/python3.10/site-packages/pymilvus/orm/connections.py", line 365, in connect_milvus
    gh._wait_for_channel_ready(timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 146, in _wait_for_channel_ready
    raise MilvusException(
pymilvus.exceptions.MilvusException: <MilvusException: (code=2, message=Fail connecting to server on host.docker.internal:19540. Timeout)>
[2024-09-11 10:45:36 +0000] [13] [ERROR] Not all workers acknowledged a successful startup. Shutting down.

One of your worker processes terminated before startup was completed. Please solve any errors experienced during startup. If you do not see an exception traceback in your error logs, try running Sanic in in a single process using --single-process or single_process=True. Once you are confident that the server is able to start without errors you can switch back to multiprocess mode.
[2024-09-11 10:45:36 +0000] [13] [INFO] Killing Sanic-Server-0-0 [494]
[2024-09-11 10:45:36 +0000] [13] [INFO] Server Stopped

**Comment by wind-c** [comment]
使用docker-compose -f docker-compose-win.yaml up遇到同样问题：
qanything-container-local  | Waiting for the backend service to start...
qanything-container-local  | 等待启动后端服务
qanything-container-local  | Waiting for the backend service to start...
qanything-container-local  | 等待启动后端服务
qanything-container-local  | Waiting for the backend service to start...
qanything-container-local  | 等待启动后端服务

**Comment by TomIsFat** [comment]
同样无法启动

**Comment by MrHeXi** [comment]
qanything-container-local  | Directory /workspace/QAnything/logs/debug_logs already exists.
qanything-container-local  | embedding和rerank服务将在CPU上运行
qanything-container-local  | Waiting for the backend service to start...
qanything-container-local  | 等待启动后端服务
qanything-container-local  | Waiting for the backend service to start...
qanything-container-local  | 等待启动后端服务
qanything-container-local  | Waiting for the backend service to start...
qanything-container-local  | 等待启动后端服务
qanything-container-local  | Waiting for the backend service to start...
qanything-container-local  | 等待启动后端服务
qanything-container-local  | Waiting for the backend service to start...
qanything-container-local  | 等待启动后端服务
qanything-container-local  | Waiting for the backend service to start...
qanything-container-local  | 等待启动后端服务
milvus-standalone-local    | [2024/09/14 01:54:35.621 +00:00] [INFO] [datacoord/compaction_policy_l0.go:33] ["start trigger l0CompactionPolicy..."]
milvus-standalone-local    | [2024/09/14 01:54:35.621 +00:00] [INFO] [datacoord/compaction_policy_single.go:49] ["start trigger singleCompactionPolicy..."]
milvus-standalone-local    | [2024/09/14 01:54:35.622 +00:00] [INFO] [datacoord/compaction_trigger.go:323] ["the length of SegmentsChanPart is 0, skip to handle compaction"] [compactionID=452533633836646703] [signal.collectionID=0] [signal.partitionID=0] [signal.segmentID=0]
qanything-container-local  | Waiting for the backend service to start...
qanything-container-local  | 等待启动后端服务
qanything-container-local  | Waiting for the backend service to start...
qanything-container-local  | 等待启动后端服务
qanything-container-local  | Waiting for the backend service to start...
qanything-container-local  | 等待启动后端服务
milvus-standalone-local    | [2024/09/14 01:54:54.811 +00:00] [WARN] [proxy/hook_interceptor.go:73] ["fail to get current user"] [error="fail to get authorization from the md, authorization:[token]"]
milvus-standalone-local    | [2024/09/14 01:54:54.812 +00:00] [INFO] [proxy/impl.go:5868] ["connect received"] [traceID=7f0ff49453359b9091b3e5d855640c83] [sdk_type=Python] [sdk_version=2.3.6] [local_time="2024-09-14 01:54:54.809961"] [user=] [host=localhost.localdomain] [db=default]
milvus-standalone-local    | [2024/09/14 01:54:54.813 +00:00] [INFO] [rootcoord/root_coord.go:931] ["received request to list databases"] [traceID=7f0ff49453359b9091b3e5d855640c83] [msgID=0]
milvus-standalone-local    | [2024/09/14 01:54:54.813 +00:00] [INFO] [rootcoord/root_coord.go:957] ["done to list databases"] [traceID=7f0ff49453359b9091b3e5d855640c83] [msgID=0] ["num of databases"=1]
milvus-standalone-local    | [2024/09/14 01:54:54.814 +00:00] [INFO] [connection/manager.go:106] ["client register"] [traceID=7f0ff49453359b9091b3e5d855640c83] [sdk_type=Python] [sdk_version=2.3.6] [local_time="2024-09-14 01:54:54.809961"] [user=] [host=localhost.localdomain] [identifier=452533654590062595] [last_active_time=2024/09/14 01:54:54.814 +00:00]
milvus-standalone-local    | [2024/09/14 01:54:54.816 +00:00] [WARN] [proxy/hook_interceptor.go:73] ["fail to get current user"] [error="fail to get authorization from the md, authorization:[token]"]
milvus-standalone-local    | [2024/09/14 01:54:54.818 +00:00] [WARN] [rootcoord/root_coord.go:1179] ["failed to describe collection"] [traceID=0656844f9580ead1ed1ec19fdee20c10] [collectionName=qanything_collection_240625] [dbName=default] [id=0] [ts=18446744073709551615] [allowUnavailable=false] [error="collection not found[database=default][collection=qanything_collection_240625]"]
qanything-container-local  | qanything后端服务已就绪!
qanything-container-local  | Time elapsed: 54 seconds.
qanything-container-local  | 已耗时: 54 秒.

启动了，但是无法访问 = =
![image](https://github.com/user-attachments/assets/97d528ff-155c-4484-bc72-3f11d0ccd39a)
![image](https://github.com/user-attachments/assets/519759b7-b9df-4563-9223-41b6be09ec74)

**Comment by cnxiaobingguo** [comment]
+1

**Comment by sea-007** [comment]
+1，解决了吗

**Comment by WoJoinGitHub** [comment]
我的解决了，程序在自动下载东西，等下载完就行了

**Comment by WoJoinGitHub** [comment]
![1726804765978](https://github.com/user-attachments/assets/18733fc7-6872-4f86-8b6e-a0da00c52ce5)

**Comment by whiletrue2009** [comment]
> 我的解决了，程序在自动下载东西，等下载完就行了

是下载的什么？  可以自己提前下载吗？

**Comment by gu-feng** [comment]
找到问题解决了，内存不足造成服务无法启动，调大内存就启动成功了

**Comment by whiletrue2009** [comment]
> 找到问题解决了，内存不足造成服务无法启动，调大内存就启动成功了

调大哪个服务的内存？how？

**Comment by gu-feng** [comment]
> > 找到问题解决了，内存不足导致服务无法启动，调大内存就启动成功了
> 
> 调大哪个服务的内存？怎么调？

docker  app设置里面resources

**Comment by wyqsss** [comment]
> > > 找到问题解决了，内存不足导致服务无法启动，调大内存就启动成功了
> > 
> > 
> > 调大哪个服务的内存？怎么调？
> 
> docker app设置里面resources

你好，内存调到多大合适呀

**Comment by 6xiaoxin** [comment]
调大内存可以解决

**Comment by Diven-xinhai** [comment]
内存拉满到16G能成功运行
![Uploading 11111.jpg…]()

**Comment by luckyxue** [comment]
内存建议20G以上

```text
一次性模式...
时间              rerank_serve...     embedding_se...     ocr_server.py       insert_files...     sanic_api.py        pdf_parser_s...     总内存(GB)            
--------------------------------------------------------------------------------------------
20241210194428      3.80GB              4.13GB              3.08GB              3.69GB              3.29GB              6.48GB              24.47GB 
```
