### ISSUE TITLE
[BUG] <title>文件解析失败

### ISSUE THREAD

**Issue by qazxswaaa** [netease-youdao/QAnything#526]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

上传文档无法解析

### 运行环境 | Environment

```Markdown
- OS:
- NVIDIA Driver:
- CUDA:
- Docker Compose:
- NVIDIA GPU Memory:
```

### QAnything日志 | QAnything logs

2024-09-20 09:31:09,458 - [PID: 577][Sanic-Server-0-0] - [Function: process_data] - ERROR - milvus insert error: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1025, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
  File "uvloop/loop.pyx", line 2039, in create_connection
  File "uvloop/loop.pyx", line 2016, in uvloop.loop.Loop.create_connection
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspace/QAnything/qanything_kernel/dependent_server/insert_files_serve/insert_files_server.py", line 108, in process_data
    chunks_number, insert_time_record = await asyncio.wait_for(
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/workspace/QAnything/qanything_kernel/utils/general_utils.py", line 166, in get_time_async_inner
    res = await func(*args, **kwargs)  # 注意这里使用 await 来调用异步函数
  File "/workspace/QAnything/qanything_kernel/core/retriever/parent_retriever.py", line 210, in insert_documents
    return await self.retriever.aadd_documents(docs, parent_chunk_size=parent_chunk_size,
  File "/workspace/QAnything/qanything_kernel/core/retriever/parent_retriever.py", line 141, in aadd_documents
    res = await self.vectorstore.aadd_documents(embed_docs, time_record=time_record)
  File "/usr/local/lib/python3.10/site-packages/langchain_core/vectorstores.py", line 153, in aadd_documents
    return await self.aadd_texts(texts, metadatas, **kwargs)
  File "/workspace/QAnything/qanything_kernel/core/retriever/vectorstore.py", line 180, in aadd_texts
    embeddings = await self.embedding_func.aembed_documents(texts)
  File "/workspace/QAnything/qanything_kernel/utils/general_utils.py", line 166, in get_time_async_inner
    res = await func(*args, **kwargs)  # 注意这里使用 await 来调用异步函数
  File "/workspace/QAnything/qanything_kernel/connector/embedding/embedding_for_online_client.py", line 40, in aembed_documents
    results = await asyncio.gather(*tasks)
  File "/workspace/QAnything/qanything_kernel/connector/embedding/embedding_for_online_client.py", line 28, in _get_embedding_async
    async with session.post(self.url, json=data) as response:
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1197, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 581, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 944, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1257, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1226, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1033, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:9001 ssl:default [Connection refused]

2024-09-20 09:31:09,468 - [PID: 577][Sanic-Server-0-0] - [Function: check_and_process] - INFO - time_record: {"parse_time": 0.45, "insert_error": true}
2024-09-20 09:31:09,479 - [PID: 577][Sanic-Server-0-0] - [Function: check_and_process] - INFO - UPDATE FILE: 202409200931, 0cabbe8b4f024ca1b28a97efc43764ba, 常见问题.docx, red

### 复现方法 | Steps To Reproduce

win11系统，docker compose命令启动

**Comment by Alreadtstart** [comment]
解决了嘛

**Comment by xiayi0409** [comment]
> 解决了嘛
您好 请问解决了吗、

**Comment by xiayi0409** [comment]
您好，请问解决了吗

> 解决了嘛
