### ISSUE TITLE
2.0无法启动，启动后端服务超时，然后报错

### ISSUE THREAD

**Issue by truthsun22** [netease-youdao/QAnything#527]
Waiting for the backend service to start...
qanything-container-local  | 等待启动后端服务
qanything-container-local  | 启动后端服务超时，自动检查日志文件 /workspace/QAnything/logs/debug_logs/main_server.log：
qanything-container-local  |   File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
qanything-container-local  |     return _default_decoder.decode(s)
qanything-container-local  |   File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
qanything-container-local  |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
qanything-container-local  |   File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
qanything-container-local  |     raise JSONDecodeError("Expecting value", s, err.value) from None
qanything-container-local  | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
qanything-container-local  |
qanything-container-local  | During handling of the above exception, another exception occurred:
qanything-container-local  |
qanything-container-local  | Traceback (most recent call last):
qanything-container-local  |   File "/usr/local/lib/python3.10/site-packages/sanic/worker/serve.py", line 117, in worker_serve
qanything-container-local  | --
qanything-container-local  |   File "/usr/local/lib/python3.10/site-packages/elastic_transport/_transport.py", line 361, in perform_request
qanything-container-local  |     body = self.serializers.loads(resp.body, resp.meta.mimetype)
qanything-container-local  |   File "/usr/local/lib/python3.10/site-packages/elastic_transport/_serializer.py", line 227, in loads
qanything-container-local  |     return self.get_serializer(mimetype).loads(data)
qanything-container-local  |   File "/usr/local/lib/python3.10/site-packages/elastic_transport/_serializer.py", line 107, in loads
qanything-container-local  |     raise SerializationError(
qanything-container-local  | elastic_transport.SerializationError: Unable to deserialize as JSON: b'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlcnJDb2RlIjo0MDAxLCJlcnJNc2ciOiLor7fmsYLmlbDmja7nu5PmnoTplJnor68iLCJwb3J0Ijo5MjEwLCJpc09ubHlHdWlsZCI6ZmFsc2UsImlhdCI6MTcyNzA2MDE4N30.z0UlMYmckIP1UAf_5Lq5fCQ3qcu52nyTPesOmeB33pg'
qanything-container-local  | [2024-09-23 02:56:27 +0000] [13] [ERROR] Not all workers acknowledged a successful startup. Shutting down.
qanything-container-local  |
qanything-container-local  | One of your worker processes terminated before startup was completed. Please solve any errors experienced during startup. If you do not see an exception traceback in your error logs, try running Sanic in in a single process using --single-process or single_process=True. Once you are confident that the server is able to start without errors you can switch back to multiprocess mode.
qanything-container-local  | [2024-09-23 02:56:27 +0000] [13] [INFO] Killing Sanic-Server-0-0 [436]
qanything-container-local  | [2024-09-23 02:56:27 +0000] [13] [INFO] Server Stopped
qanything-container-local  | 检测到错误信息，请查看上面的输出。

**Comment by truthsun22** [comment]
找到原因了，是访问host.docker.internal不通，我换成WSL的IP地址就可以了，请问host.docker.internal不通的问题怎么解决？我的机器是win11+docker desktop。
然后上传解析word又出问题了，感觉2.0版本问题太多了
2024-09-24 09:12:27,422 - [PID: 516][Sanic-Server-0-0] - [Function: process_data] - ERROR - Timeout: milvus insert took longer than 300 seconds
2024-09-24 09:12:27,430 - [PID: 516][Sanic-Server-0-0] - [Function: check_and_process] - ERROR - MySQL或Milvus 连接异常：object of type 'NoneType' has no len()
2024-09-24 09:12:27,506 - [PID: 516][Sanic-Server-0-0] - [Function: check_and_process] - ERROR - process_files Error Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 608, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 976, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/usr/local/lib/python3.10/site-packages/aiohttp/streams.py", line 640, in read
    await self._waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/QAnything/qanything_kernel/utils/general_utils.py", line 166, in get_time_async_inner
    res = await func(*args, **kwargs)  # 注意这里使用 await 来调用异步函数
  File "/workspace/QAnything/qanything_kernel/core/retriever/parent_retriever.py", line 210, in insert_documents
    return await self.retriever.aadd_documents(docs, parent_chunk_size=parent_chunk_size,
  File "/workspace/QAnything/qanything_kernel/core/retriever/parent_retriever.py", line 141, in aadd_documents
    res = await self.vectorstore.aadd_documents(embed_docs, time_record=time_record)
  File "/usr/local/lib/python3.10/site-packages/langchain_core/vectorstores.py", line 153, in aadd_documents
    return await self.aadd_texts(texts, metadatas, **kwargs)
  File "/workspace/QAnything/qanything_kernel/core/retriever/vectorstore.py", line 180, in aadd_texts
    embeddings = await self.embedding_func.aembed_documents(texts)
  File "/workspace/QAnything/qanything_kernel/utils/general_utils.py", line 166, in get_time_async_inner
    res = await func(*args, **kwargs)  # 注意这里使用 await 来调用异步函数
  File "/workspace/QAnything/qanything_kernel/connector/embedding/embedding_for_online_client.py", line 40, in aembed_documents
    results = await asyncio.gather(*tasks)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspace/QAnything/qanything_kernel/dependent_server/insert_files_serve/insert_files_server.py", line 108, in process_data
    chunks_number, insert_time_record = await asyncio.wait_for(
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/QAnything/qanything_kernel/dependent_server/insert_files_serve/insert_files_server.py", line 187, in check_and_process
    status, content_length, chunks_number, msg = await process_data(retriever, milvus_kb,
  File "/workspace/QAnything/qanything_kernel/utils/general_utils.py", line 166, in get_time_async_inner
    res = await func(*args, **kwargs)  # 注意这里使用 await 来调用异步函数
  File "/workspace/QAnything/qanything_kernel/dependent_server/insert_files_serve/insert_files_server.py", line 118, in process_data
    milvus_kb.delete_expr(expr)
  File "/workspace/QAnything/qanything_kernel/utils/general_utils.py", line 148, in get_time_inner
    res = func(*arg, **kwargs)
  File "/workspace/QAnything/qanything_kernel/core/retriever/vectorstore.py", line 298, in delete_expr
    if len(self.get_local_chunks(expr)) == 0:
TypeError: object of type 'NoneType' has no len()

**Comment by zhu1987** [comment]
@truthsun22 请问解决了吗？我也是这个问题
![image](https://github.com/user-attachments/assets/0b1e9026-0138-4422-8c2f-d8d71312b426)
