### ISSUE TITLE
[BUG] <title>启动后端服务超时 Can't connect to MySQL server on 'localhost:3316'

### ISSUE THREAD

**Issue by xiayi0409** [netease-youdao/QAnything#534]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

**启动后端服务超时Can't connect to MySQL server on 'localhost:3316'**

qanything-container-local  | Waiting for the backend service to start...
qanything-container-local  | 等待启动后端服务
qanything-container-local  | 启动后端服务超时，自动检查日志文件 /workspace/QAnything/logs/debug_logs/main_server.log：
qanything-container-local  | [2024-09-28 06:16:43 +0000] [987] [INFO]   > templating [jinja2==3.1.4]
qanything-container-local  | [2024-09-28 06:16:44 +0000] [987] [ERROR] 2003 (HY000): Can't connect to MySQL server on 'localhost:3316' (111)
qanything-container-local  | Traceback (most recent call last):
qanything-container-local  |   File "/usr/local/lib/python3.10/site-packages/mysql/connector/connection_cext.py", line 308, in _open_connection
qanything-container-local  |     self._cmysql.connect(**cnx_kwargs)
qanything-container-local  | _mysql_connector.MySQLInterfaceError: Can't connect to MySQL server on 'localhost:3316' (111)
qanything-container-local  | 
qanything-container-local  | The above exception was the direct cause of the following exception:
qanything-container-local  | 
qanything-container-local  | Traceback (most recent call last):
qanything-container-local  |   File "/usr/local/lib/python3.10/site-packages/sanic/worker/serve.py", line 117, in worker_serve
qanything-container-local  | --
qanything-container-local  |     self.connect(**kwargs)
qanything-container-local  |   File "/usr/local/lib/python3.10/site-packages/mysql/connector/abstracts.py", line 1237, in connect
qanything-container-local  |     self._open_connection()
qanything-container-local  |   File "/usr/local/lib/python3.10/site-packages/mysql/connector/connection_cext.py", line 313, in _open_connection
qanything-container-local  |     raise get_mysql_exception(
qanything-container-local  | mysql.connector.errors.DatabaseError: 2003 (HY000): Can't connect to MySQL server on 'localhost:3316' (111)
qanything-container-local  | [2024-09-28 06:16:44 +0000] [13] [ERROR] Not all workers acknowledged a successful startup. Shutting down.
qanything-container-local  | 
qanything-container-local  | One of your worker processes terminated before startup was completed. Please solve any errors experienced during startup. If you do not see an exception traceback in your error logs, try running Sanic in in a single process using --single-process or single_process=True. Once you are confident that the server is able to start without errors you can switch back to multiprocess mode.
qanything-container-local  | [2024-09-28 06:16:44 +0000] [13] [INFO] Killing Sanic-Server-0-0 [987]
qanything-container-local  | [2024-09-28 06:16:44 +0000] [13] [INFO] Server Stopped
qanything-container-local  | 检测到错误信息，请查看上面的输出。
qanything-container-local exited with code 1

### 期望行为 | Expected Behavior

成功运行

### 运行环境 | Environment

```Markdown
- OS:
- NVIDIA Driver:
- CUDA:
- Docker Compose:
- NVIDIA GPU Memory:
```

**Comment by niko-1573** [comment]
同问

**Comment by xiaokuang95** [comment]
我也遇到了这个问题，我解决了，请检查 insert_files_server.log的日志，看是不是es连不上，如果是，需要改动python代码 qanything_kernel\configs\model_config.py:131 代码改为ES_URL = 'http://es-container-local:9200/' 就能正常跑起来了
