### ISSUE TITLE
[BUG] npm run install报错failed to install npm dependencies

### ISSUE THREAD

**Issue by Vickzhang** [netease-youdao/QAnything#54]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

run_for_local.sh 脚本1/8-4/8项均正常启动，在5/8报错，应该是node的有个依赖包无法安装：

> 2118 timing command:install Completed in 45793ms
2119 verbose stack Error: command failed
2119 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/nodejs/node-v18.19.0-linux-x64/lib/node_modules/npm/node_modules/@npmcli/promis
e-spawn/lib/index.js:53:27)
2119 verbose stack     at ChildProcess.emit (node:events:517:28)
2119 verbose stack     at maybeClose (node:internal/child_process:1098:16)
2119 verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:303:5)
2120 verbose pkgid esbuild@0.19.11
2121 verbose cwd /workspace/qanything_local/front_end
2122 verbose Linux 3.10.0-1160.el7.x86_64
2123 verbose node v18.19.0
2124 verbose npm  v10.2.3
2125 error code 1
2126 error path /workspace/qanything_local/front_end/node_modules/esbuild
2127 error command failed
2128 error command sh -c node install.js
2129 error node:internal/errors:865
2129 error   const err = new Error(message);
2129 error               ^
2129 error
2129 error Error: Command failed: /workspace/qanything_local/front_end/node_modules/esbuild/bin/esbuild --version
2129 error     at checkExecSyncError (node:child_process:890:11)
2129 error     at Object.execFileSync (node:child_process:926:15)
2129 error     at validateBinaryVersion (/workspace/qanything_local/front_end/node_modules/esbuild/install.js:99:28)
2129 error     at /workspace/qanything_local/front_end/node_modules/esbuild/install.js:286:5 {
2129 error   status: null,
2129 error   signal: 'SIGSEGV',
2129 error   output: [ null, Buffer(0) [Uint8Array] [], Buffer(0) [Uint8Array] [] ],
2129 error   pid: 2003,
2129 error   stdout: Buffer(0) [Uint8Array] [],
2129 error   stderr: Buffer(0) [Uint8Array] []
2129 error }
2129 error
2129 error Node.js v18.19.0
2130 verbose exit 1
2131 timing npm Completed in 46052ms

### 期望行为 | Expected Behavior

正确启动

### 运行环境 | Environment

```Markdown
- OS: CentOS 7.9
- NVIDIA Driver:535.129.03
- CUDA:12.2
- Docker Compose: 2.24.1
- NVIDIA GPU Memory: 24G+24G
```

**Comment by qurikuduo** [comment]
我也遇到了同样的错误。

**Comment by Nydaym** [comment]
在run_for_local.sh的89行以后加上
```bash
# Modify npm registry
npm config set registry https://registry.npmmirror.com/

**Comment by Nydaym** [comment]
> > 在run_for_local.sh的89行以后加上
> > ```shell
> > # Modify npm registry
> > npm config set registry https://registry.npmmirror.com/
> > ```
> 
> 我这边修改后还是跑不通

试试重新build一下项目呢？可能之前的缓存啥的有些问题删除试试，我之前是很多包下载不下来换了这个新的源就好了，可能你的问题和我不一样。

**Comment by qurikuduo** [comment]
我的操作系统是 Ubuntu 18.04，我看了下前端用的是Vue. 我的新服务器，没有安装nodejs。
我安装了nodejs，但是支持的最高版本只能是17.9.0。
然后继续执行 bash run.sh 0,1 ，现在不会报楼主同样的错误了。现在的报错是：
`

npm notice 
qanything-container-local  | npm notice New minor version of npm available! 10.2.3 -> 10.3.0
qanything-container-local  | npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.3.0
qanything-container-local  | npm notice Run npm install -g npm@10.3.0 to update!
qanything-container-local  | npm notice 
qanything-container-local  | npm ERR! process terminated
qanything-container-local  | npm ERR! signal SIGTERM
qanything-container-local  | 
qanything-container-local  | npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2024-01-23T06_21_30_381Z-debug-0.log
qanything-container-local  | Failed to install npm dependencies.
qanything-container-local exited with code 1

`

**Comment by qurikuduo** [comment]
@Vickzhang 你的服务器上安装了nodeJs了吗？

**Comment by qurikuduo** [comment]
> 在run_for_local.sh的89行以后加上
> 
> ```shell
> # Modify npm registry
> npm config set registry https://registry.npmmirror.com/
> ```

我再按照这个方法设置了一下，然后进入到 front_end 目录后，运行 npm install 手工安装了一下 packages，目前一切正常了。
`qanything-container-local  | [npm run build] build successfully(6/8)
qanything-container-local  | Waiting for the front-end service to start...
qanything-container-local  | 等待启动前端服务
qanything-container-local  | 
qanything-container-local  | > ai-demo@1.0.1 serve
qanything-container-local  | > vite preview --port 5052
qanything-container-local  | 
qanything-container-local  | The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
qanything-container-local  | Waiting for the front-end service to start...
qanything-container-local  | 等待启动前端服务
qanything-container-local  |   ➜  Local:   http://localhost:5052/qanything
qanything-container-local  |   ➜  Network: http://172.25.0.6:5052/qanything
qanything-container-local  | The front-end service is ready!...(7/8)
qanything-container-local  | 前端服务已就绪!...(7/8)
qanything-container-local  | Time elapsed: 32 seconds.
qanything-container-local  | 已耗时: 32 秒.
qanything-container-local  | The triton service is ready!, now you can use the qanything service. (8/8)
qanything-container-local  | Triton服务已准备就绪！现在您可以使用qanything服务。（8/8)
qanything-container-local  | Time elapsed: 32 seconds.
qanything-container-local  | 已耗时: 32 秒.
`
@Vickzhang 供你参考。
我主要遇到的问题：
1.服务器未安装nodejs，因为ubuntu 18.04系统较老旧，找支持的nodejs最高版本花了一些时间，目前结论：v17.9.0
2.未将npm的源设置为 https://registry.npmmirror.com/ ，按照 @Nydaym 的提示，将源设置正确。重新安装依赖即可。
感谢 @Nydaym

**Comment by qurikuduo** [comment]
New PR created.

**Comment by Vickzhang** [comment]
> > 在run_for_local.sh的89行以后加上
> > ```shell
> > # Modify npm registry
> > npm config set registry https://registry.npmmirror.com/
> > ```
> 
> 我再按照这个方法设置了一下，然后进入到 front_end 目录后，运行 npm install 手工安装了一下 packages，目前一切正常了。 `qanything-container-local | [npm run build] build successfully(6/8) qanything-container-local | Waiting for the front-end service to start... qanything-container-local | 等待启动前端服务 qanything-container-local | qanything-container-local | > ai-demo@1.0.1 serve qanything-container-local | > vite preview --port 5052 qanything-container-local | qanything-container-local | The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details. qanything-container-local | Waiting for the front-end service to start... qanything-container-local | 等待启动前端服务 qanything-container-local | ➜ Local: http://localhost:5052/qanything qanything-container-local | ➜ Network: http://172.25.0.6:5052/qanything qanything-container-local | The front-end service is ready!...(7/8) qanything-container-local | 前端服务已就绪!...(7/8) qanything-container-local | Time elapsed: 32 seconds. qanything-container-local | 已耗时: 32 秒. qanything-container-local | The triton service is ready!, now you can use the qanything service. (8/8) qanything-container-local | Triton服务已准备就绪！现在您可以使用qanything服务。（8/8) qanything-container-local | Time elapsed: 32 seconds. qanything-container-local | 已耗时: 32 秒. ` @Vickzhang 供你参考。 我主要遇到的问题： 1.服务器未安装nodejs，因为ubuntu 18.04系统较老旧，找支持的nodejs最高版本花了一些时间，目前结论：v17.9.0 2.未将npm的源设置为 https://registry.npmmirror.com/ ，按照 @Nydaym 的提示，将源设置正确。重新安装依赖即可。 感谢 @Nydaym

@qurikuduo 在docker 跑的，Dockerfile里面是有执行nodejs 18.19安装的，进入container里面测了也是有node 18.19

**Comment by qurikuduo** [comment]
> > > 在run_for_local.sh的89行以后加上
> > > ```shell
> > > # Modify npm registry
> > > npm config set registry https://registry.npmmirror.com/
> > > ```
> > 
> > 
> > 我再按照这个方法设置了一下，然后进入到 front_end 目录后，运行 npm install 手工安装了一下 packages，目前一切正常了。 `qanything-container-local | [npm run build] build successfully(6/8) qanything-container-local | Waiting for the front-end service to start... qanything-container-local | 等待启动前端服务 qanything-container-local | qanything-container-local | > ai-demo@1.0.1 serve qanything-container-local | > vite preview --port 5052 qanything-container-local | qanything-container-local | The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details. qanything-container-local | Waiting for the front-end service to start... qanything-container-local | 等待启动前端服务 qanything-container-local | ➜ Local: http://localhost:5052/qanything qanything-container-local | ➜ Network: http://172.25.0.6:5052/qanything qanything-container-local | The front-end service is ready!...(7/8) qanything-container-local | 前端服务已就绪!...(7/8) qanything-container-local | Time elapsed: 32 seconds. qanything-container-local | 已耗时: 32 秒. qanything-container-local | The triton service is ready!, now you can use the qanything service. (8/8) qanything-container-local | Triton服务已准备就绪！现在您可以使用qanything服务。（8/8) qanything-container-local | Time elapsed: 32 seconds. qanything-container-local | 已耗时: 32 秒. ` @Vickzhang 供你参考。 我主要遇到的问题： 1.服务器未安装nodejs，因为ubuntu 18.04系统较老旧，找支持的nodejs最高版本花了一些时间，目前结论：v17.9.0 2.未将npm的源设置为 https://registry.npmmirror.com/ ，按照 @Nydaym 的提示，将源设置正确。重新安装依赖即可。 感谢 @Nydaym
> 
> @qurikuduo 在docker 跑的，Dockerfile里面是有执行nodejs 18.19安装的，进入container里面测了也是有node 18.19

那看起来跟我遇到的不是同一个问题。尝试进入到 front_end 目录里手工安装一下依赖试试？看看能不能抓到是哪个包缺失。

**Comment by 01000100GT** [comment]
docker-compose-linux.yaml
    command: /bin/bash -c " npm config set registry https://registry.npmmirror.com ;npm config get registry ;  /workspace/qanything_local/scripts/run_for_local.sh "
把command 改成这 应该就可以了

**Comment by 01000100GT** [comment]
docker-compose-linux.yaml
  qanything_local:
       command: /bin/bash -c " npm config set registry https://registry.npmmirror.com/ ;npm config get registry ; /workspace/qanything_local/scripts/run_for_local.sh "
把command 改成这 应该就可以了

**Comment by hao203** [comment]
我也是这个问题，试了很多次根本解决不了。真的无语

**Comment by hao203** [comment]
经过反复折腾，最终，用yarn解决了这个问题，参考
\scripts\run_for_local_option.sh 这个文件，将npm install相关的代码改成yarn的。
`# 安装依赖
echo "Waiting for [npm run install]（5/8)"

npm config set registry https://registry.npmmirror.com
npm install -g yarn
yarn config set registry https://registry.npmmirror.com

timeout $timeout_time yarn install`
![image](https://github.com/netease-youdao/QAnything/assets/6681974/96ab7c64-b127-496c-98cc-75eb5531cb14)
本人测试环境win11+wsl2+docker

**Comment by Ikaros-521** [comment]
直接换cnpm装，超时180秒不一定能装好，可以延长等待时间。最后还是装不好，直接进容器装，结束
\scripts\run_for_local_option.sh 改
```
# 安装依赖
echo "Waiting for [npm run install]（5/8)"
npm config set registry https://registry.npmmirror.com
npm install -g cnpm
timeout 180 cnpm install
```
![image](https://github.com/netease-youdao/QAnything/assets/40910637/4bcbdff5-945b-4662-b910-a5a0c6fbb4a2)

**Comment by hao203** [comment]
> 直接换cnpm装，超时180秒不一定能装好，可以延长等待时间。最后还是装不好，直接进容器装，结束 \scripts\run_for_local_option.sh 改
> 
> ```
> # 安装依赖
> echo "Waiting for [npm run install]（5/8)"
> npm config set registry https://registry.npmmirror.com
> npm install -g cnpm
> timeout 180 cnpm install
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/40910637/305873812-4bcbdff5-945b-4662-b910-a5a0c6fbb4a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NTM4ODUsIm5iZiI6MTcwODY1MzU4NSwicGF0aCI6Ii80MDkxMDYzNy8zMDU4NzM4MTItNGJjYmRmZjUtOTQ1Yi00NjYyLWI5MTAtYTVhMGM2ZmJiNGEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDAxNTk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0NjRlYzRlYTljN2RkYzYwOWVkOGRiZmQxYTdlY2U0NjFkZGVjZGM3Y2U5ZThkMTBlZjhhMGE2NDdmNDQ0YjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.afCHmF2_r5zvxTzWFxwHY5Ek6VEZbU32dSUotxSdUo0)

我试过你这手法。还是报错。后面换了yarn

**Comment by Ikaros-521** [comment]
> > 直接换cnpm装，超时180秒不一定能装好，可以延长等待时间。最后还是装不好，直接进容器装，结束 \scripts\run_for_local_option.sh 改
> > ```
> > # 安装依赖
> > echo "Waiting for [npm run install]（5/8)"
> > npm config set registry https://registry.npmmirror.com
> > npm install -g cnpm
> > timeout 180 cnpm install
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![image](https://private-user-images.githubusercontent.com/40910637/305873812-4bcbdff5-945b-4662-b910-a5a0c6fbb4a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NTM4ODUsIm5iZiI6MTcwODY1MzU4NSwicGF0aCI6Ii80MDkxMDYzNy8zMDU4NzM4MTItNGJjYmRmZjUtOTQ1Yi00NjYyLWI5MTAtYTVhMGM2ZmJiNGEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDAxNTk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0NjRlYzRlYTljN2RkYzYwOWVkOGRiZmQxYTdlY2U0NjFkZGVjZGM3Y2U5ZThkMTBlZjhhMGE2NDdmNDQ0YjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.afCHmF2_r5zvxTzWFxwHY5Ek6VEZbU32dSUotxSdUo0)
> 
> 我试过你这手法。还是报错。后面换了yarn

看样子都是折磨

**Comment by cloudyangel** [comment]
刚刚也遇到了这个问题，我的解决方案是从docker desktop 中进去到 qanything_container_local 这个容器，手动删除node modules 文件夹，清除cache                    npm cache clean --force          然后执行命令  npm install； 示意图如下
![image](https://github.com/netease-youdao/QAnything/assets/31439796/5a857c93-42ea-4f46-a2e9-8fe585b1cb1c)
