### ISSUE TITLE
[BUG] The application encountered an unexpected error and could not continue

### ISSUE THREAD

**Issue by Eternal88** [netease-youdao/QAnything#85]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

curl 'http://192.168.80.120:5052/api/local_doc_qa/local_doc_chat' \
  -H 'Accept: text/event-stream,application/json, text/event-stream' \
  -H 'Accept-Language: zh-CN,zh;q=0.9' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json' \
  -H 'Origin: http://192.168.80.120:5052' \
  -H 'Referer: http://192.168.80.120:5052/qanything' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36' \
  --data-raw '{"user_id":"zzp","kb_ids":["KB8a4b424d2c8141d4a13b8fdd4e82978a"],"history":[],"question":"提取接口","streaming":true}' \
  --compressed \
  --insecure

### 运行环境 | Environment

```Markdown
- OS:
- NVIDIA Driver:
- CUDA:
- Docker Compose:
- NVIDIA GPU Memory:
```

### QAnything日志 | QAnything logs

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "handle_request", line 132, in handle_request
    "_asgi_lifespan",
  File "/usr/local/lib/python3.10/dist-packages/sanic/response/types.py", line 547, in stream
    await self.streaming_fn(self)
  File "/workspace/qanything_local/qanything_kernel/qanything_server/handler.py", line 355, in generate_answer
    for resp, next_history in local_doc_qa.get_knowledge_based_answer(
  File "/workspace/qanything_local/qanything_kernel/core/local_doc_qa.py", line 236, in get_knowledge_based_answer
    for answer_result in self.llm.generatorAnswer(prompt=prompt,
  File "/workspace/qanything_local/qanything_kernel/connector/llm/llm_for_local.py", line 77, in generatorAnswer
    for stream_resp in self.stream_chat(prompt, history=history[:-1]):
  File "/workspace/qanything_local/qanything_kernel/connector/llm/llm_for_local.py", line 143, in stream_chat
    for res in self.retry_stream_requests(data_raw=data_raw, headers={"User-Agent": "fastchat Client"}):
  File "/workspace/qanything_local/qanything_kernel/connector/llm/llm_for_local.py", line 147, in retry_stream_requests
    response = requests.post(
  File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='0.0.0.0', port=36001): Read timed out. (read timeout=60)
INFO:debug_logger:list_kbs zzp
INFO:debug_logger:all kb infos: [{'kb_id': 'KB8a4b424d2c8141d4a13b8fdd4e82978a', 'kb_name': '关键词提问'}]
INFO:debug_logger:list_kbs zzp
INFO:debug_logger:all kb infos: [{'kb_id': 'KB8a4b424d2c8141d4a13b8fdd4e82978a', 'kb_name': '关键词提问'}]

**Comment by bikeRiver** [comment]
遇到了同样的问题，文档上传都是解析成功的。提问时候回复调用的接口报500.查看 api.log也是
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='0.0.0.0', port=36001): Read timed out. (read timeout=60)
![image](https://github.com/netease-youdao/QAnything/assets/20725582/a2a91536-2208-42bd-86fe-fa3a488dedfd)
